### ISSUE TITLE
Feature Request - Set Demo Mode UI features

### ISSUE THREAD

**Issue by mattwakeman** [yume-chan/ya-webadb#220]
When taking screen shots and producing content for Playstore, various demo UI features are used. e.g set a specific time, task bar icons, battery level, wifi level etc. 

More derails here: 
https://android.googlesource.com/platform/frameworks/base/+/master/packages/SystemUI/docs/demo_mode.md 

Can we please get a demo mode tab or add some options to screen capture tab?

Thanks

**Comment by yume-chan** [comment]
I added most demo mode options in 3e982fbd1e88e70323297c36d4ef4ffadbca0d64. 

![image](https://user-images.githubusercontent.com/1330321/102755469-6fd9a280-43a9-11eb-8bdb-40bb91f27516.png)

However:

1. The link you provided contains some old and incorrect information. The protocol may be changed between Android versions, but I can only implement based on latest Android source code.
2. From my limited testing, supporting for demo mode also varies between device vendors. Many of them completely ignores mobile signal related settings, I didn't find any solutions yet.

If you found something that's working on other tools, but now here, please open a new issue.

**Comment by mattwakeman** [comment]
Thank you
