### ISSUE TITLE
There is no version of this mini-css-extract-plugin": "1.2.2"

### ISSUE THREAD

**Issue by YYJavaGit** [yume-chan/ya-webadb#234]
There is no version of this mini-css-extract-plugin": "1.2.2"
packages/webpack-config/package.json: 22line

**Comment by YYJavaGit** [comment]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/mini-css-extract-plugin@1.2.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'webpack-config'
npm ERR! notarget

https://www.npmjs.com/package/mini-css-extract-plugin?activeTab=versions

Modified this version to be normal

**Comment by yume-chan** [comment]
npm ERR! notarget No matching version found for **@types/mini-css-extract-plugin**@1.2.2.

https://www.npmjs.com/package/@types/mini-css-extract-plugin?activeTab=versions

Please verify you are using the official npm repository.
