### ISSUE TITLE
Any trick to connect to emulators?

### ISSUE THREAD

**Issue by l2aelba** [yume-chan/ya-webadb#243]
I was wondering about does it possible to connect to emulators like Bluestack / Nox / LD Player or something?

Or any trick for it? like by installed some program or something to fake it.

Thanks

**Comment by yume-chan** [comment]
I don't know about those third-party emulators, but at least for the official [Android Emulator](https://developer.android.com/studio/run/emulator), it's possible, with some help of websockify.

![image](https://user-images.githubusercontent.com/1330321/105126852-9579d900-5b1a-11eb-97f5-d3caf8275a99.png)

If the ones you have mentioned can also be automatically picked up by a normal `adb`, then this method will also apply to them.

It's a little complex and requires some programming skill, please tell me if you want to know the details, then I will find some spare time to organize the steps and post here.
