### ISSUE TITLE
Connecting to official Android emulator

### ISSUE THREAD

**Issue by habacuqueboy** [yume-chan/ya-webadb#260]
Hello

On issue #243 was mentioned that is possible to connect to the android emulator, with the help of websocketify. What are the details on this method ?

thank you

**Comment by yume-chan** [comment]
#243 has been moved to #245.

I'm currently on vacation, I will post steps there once back to work.

**Comment by habacuqueboy** [comment]
> #243 has been moved to #245.
> 
> I'm currently on vacation, I will post steps there once back to work.

Thank you for the attention , take a good rest :)

**Comment by yume-chan** [comment]
I posted detailed steps in https://github.com/yume-chan/ya-webadb/discussions/245#discussioncomment-384030. If you still have problems, please also reply there.
