### ISSUE TITLE
scrcpy can't connect

### ISSUE THREAD

**Issue by sosopop** [yume-chan/ya-webadb#262]
I use ws backend, scrcpy cant connect same old version adbd by use reverse type
can u mplement scrcpy forward in this project

**Comment by yume-chan** [comment]
Just to make sure, you connected to a real device using ADB over WiFi?

**Comment by sosopop** [comment]
是的

我参照scrcpy代码中server forward的实现方式简单修改了测试了下，可以正常通讯并显示：
        for(let i = 0; i < 100; i++ ) {
            try {
                await new Promise(resolve => {
                    window.setTimeout(resolve, 100);
                });
                let videoSocket = await device.createSocket('localabstract:scrcpy');
                videoStream = new AdbBufferedStream(videoSocket);
                videoStream.read(1);
                let ctrlSocket = await device.createSocket('localabstract:scrcpy');
                controlStream = new AdbBufferedStream(ctrlSocket);
                break;
            } catch (error) {
                console.log("stream open failed");
            }
        }

**Comment by yume-chan** [comment]
对，实现起来不是很难，但是我要做一个设置界面，因为 ws 后端并不是一定对应 ADB over WiFi

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/108687991-59c79a00-7532-11eb-98ff-22cbceba149f.png)

在 scrcpy 页面加了个设置面板，修改设置会在下一次连接的时候生效
