### ISSUE TITLE
有些设备解析出来图像的宽高不正确

### ISSUE THREAD

**Issue by sosopop** [yume-chan/ya-webadb#265]
在rk3399芯片的设备上使用的OMX.rk.video_encoder.avc编码器返回的数据解析sps的时候，获取到的宽高都为0，注释掉if (pts === NoPts)区块内的代码是正常的，只不过没法动态旋转屏幕了
这是nalu数据 00000001274200288d6804404de5e1000003000100000300780f107a800000000128ce3248

**Comment by yume-chan** [comment]
我之前就发现我写的 nalu 解析逻辑是有问题的，之前在 dev 分支上 a3ef2fe30a0cffa2a08d2fac7d1d104d6b07f471 我写了个新的，但是一直没找到文件来测试

试了下那个新的可以正确解析你给的这个 nalu，我就先把它合到 master 分支了，可以再试下
