### ISSUE TITLE
Error: access denied when trying to connect to the device

### ISSUE THREAD

**Issue by roipoussiere** [yume-chan/ya-webadb#270]
Despite the fact that I can use adb via USB and wifi, use scrcpy etc. via a terminal, I can't connect to my device with WebADB, I don't know why:

![image](https://user-images.githubusercontent.com/1665542/109094326-0dd74980-771a-11eb-82ca-916a2d406e1e.png)

Note that the Android device appears under the *available devices* section.

---

- PC: Kubuntu 20.04 & Chromium v. 88
- Mobile: Android 6.0.1 on Samsung Galaxy XCover 3

**Comment by yume-chan** [comment]
Make sure native ADB is not running (`adb kill-server`)

**Comment by roipoussiere** [comment]
Tried `adb kill-server`, same result.

**Comment by yume-chan** [comment]
Can you verify by running `ps -ef | grep adb`?

If `adb` is not running, try open `chrome://usb-internals/`, find your device in "Devices" tab and click "Inspect", click every button in opened tab, does any one report errors?

**Comment by yume-chan** [comment]
Closing since no response.
