### ISSUE TITLE
基于ws的backend，在非127.0.0.1的网址下无法下载文件

### ISSUE THREAD

**Issue by sosopop** [yume-chan/ya-webadb#274]
如使用[http://192.168.5.194:9000/#/file-manager](http://192.168.5.194:9000/#/file-manager)调试页面，点击文件会另外会弹出streamsaver的一个窗口
![download](https://user-images.githubusercontent.com/3153828/109446626-fe8b2f80-7a7c-11eb-9422-7bfacff3ed98.png)

**Comment by yume-chan** [comment]
StreamSaver 是用 Service Worker 下载文件的，Service Worker 需要 HTTPS 环境。

你可以在你的服务器程序里配置 SSL，或者把你的不安全地址加到 chrome://flags/#unsafely-treat-insecure-origin-as-secure 里

**Comment by sosopop** [comment]
thx
