### ISSUE TITLE
parseScrcpyOutput匹配空行有个错误

### ISSUE THREAD

**Issue by sosopop** [yume-chan/ya-webadb#276]
while(line = lines.next()) 匹配到空字符串""的时候也会退出循环，导致scrcpy经常启动的时候提示错误（ws连接）。
修改成while ((line = lines.next()) !== undefined) 正常

**Comment by yume-chan** [comment]
有完整的输出日志吗？

我没有仔细看 scrcpy 的代码但是我不记得它会输出空行

当然如果你确定这么改不会影响其它地方的话我也接受 pr

**Comment by yume-chan** [comment]
Changed in 916405c8b79714dbfb60d49396d7edc5228399ee
