### ISSUE TITLE
Npm package for @yume-chan/adb-backend-ws not found

### ISSUE THREAD

**Issue by ehte92** [yume-chan/ya-webadb#302]
When I try to install the npm package for adb-backend-ws, I get the following errors.

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@yume-chan%2fadb-backend-ws - Not found
npm ERR! 404
npm ERR! 404  '@yume-chan/adb-backend-ws@^0.0.9' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by yume-chan** [comment]
Yes, it's not published.

It's not on my original design goal (an ADB client using WebUSB API), and not easy to use (requires running extra software on device), I added it only to demonstrate the possibility of other backends. It's not suitable for real-world usage so I don't want to publish it.

**Comment by ehte92** [comment]
Thank you for the quick response. I just have a quick question, it would be great if you could help me. I was trying to run a specific shell command, but I do not want to show the whole terminal and everything. I just wanted to run a shell command on a button click. If you may be so kind as to guide me on how can I achieve that.

**Comment by yume-chan** [comment]
If you only want to wait until it exits and get the entire output, use `device.childProcess.exec`:

https://github.com/yume-chan/ya-webadb/blob/36b925d6a37feb85136099e5df76349e81442c76/packages/adb/src/adb.ts#L203-L205

If you need to write into its stdin or stream its output in realtime, use `device.childProcess.spawn`:

https://github.com/yume-chan/ya-webadb/blob/09c9764aa84fe0098342283a61758354ba2613b6/packages/demo/src/routes/scrcpy/server/client.ts#L327-L352

https://github.com/yume-chan/ya-webadb/blob/09c9764aa84fe0098342283a61758354ba2613b6/packages/demo/src/routes/scrcpy/server/client.ts#L366

If you want separate stdout and stderr, or the exit code, your device must support the `shell_v2` feature.

**Comment by ehte92** [comment]
Thank you so much for the response. I was able to achieve what I wanted to, and I am eternally grateful.
