### ISSUE TITLE
Project won't work in production after importing

### ISSUE THREAD

**Issue by ehte92** [yume-chan/ya-webadb#303]
Hi Yume Chan,

After implementing the package, when I build my create-react-app project and serve the build folder using serve -s build. I get a blank page but I do get an error that I see in the console is this weird error.

`
Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at Object.<anonymous> (crypto.ts:5)
    at a ((index):1)
    at Module.2203 (main.a1a47e62.chunk.js:31192)
    at a ((index):1)
    at t ((index):1)
    at Array.r [as push] ((index):1)
    at main.a1a47e62.chunk.js:1

`

I do not understand where this is coming from because I have not used the crypto package in my package.json file.

If you could help then I would be really grateful.

**Comment by yume-chan** [comment]
See babel/babel#13109

**Comment by yume-chan** [comment]
Closing since no response.
