### ISSUE TITLE
感觉可以写一个 基于adb的版本 感觉更通用？

### ISSUE THREAD

**Issue by bobiscool** [yume-chan/ya-webadb#319]
感觉可以写一个 基于adb的版本 感觉更通用？

**Comment by bobiscool** [comment]
额  就是你的项目是 基于webusb的 我想说的是基于原生的adb，特别是scrcpy控制 + web这块 感觉很通用

**Comment by yume-chan** [comment]
能详细说说吗？比如怎么调用原生 adb，调用原生 scrcpy？

Simon Chan

________________________________

**Comment by bobiscool** [comment]
额  其实就是 你这块 是webusb + adb + scrcpy

我的意思是说 改造成    本地adb + scrcpy

我看你还自己为了 webusb 实现了adb 内部的一些东西 👍

**Comment by drauggres** [comment]
@bobiscool, there is already an adb client implementation for nodejs: https://github.com/openstf/adbkit.

But I would love to see another version based on @yume-chan's code, since adbkit in not actively developed.

**Comment by bobiscool** [comment]
> @bobiscool, there is already an adb client implementation for nodejs: https://github.com/openstf/adbkit.
> 
> But I would love to see another version based on @yume-chan's code, since adbkit in not actively developed.

 you can read chinese. 赞

**Comment by yume-chan** [comment]
> 我的意思是说 改造成 本地adb + scrcpy

@bobiscool 那为什么不直接用原生 adb + scrcpy？我需要实现哪部分？

**Comment by yume-chan** [comment]
> But I would love to see another version based on @yume-chan's code

@drauggres I have investigated that idea, and with https://github.com/thegecko/webusb,  a drop-in replacement of browser's WebUSB API, I believe it's pretty easy to implement another backend with this package.
