### ISSUE TITLE
Run it as a server

### ISSUE THREAD

**Issue by marospekarik** [yume-chan/ya-webadb#329]
Hi, thanks for amazing work! I have a usecase where I need to use it as a server. Is there some easy way we could support that?

**Comment by yume-chan** [comment]
I can't think of any valid use case of that. To connect to a remote ADB server with native ADB binary, you can create an SSH tunnel. To access some feature of ADB in a browser, you can write a server to spawn the native ADB binary, read the output and send to web frontend with any format you like.

There is no need to use a custom ADB implementation in browser if you have native ADB.

Simon Chan

________________________________
From: Maroš Pekárik ***@***.***>
Sent: Thursday, May 13, 2021 8:28:07 PM
To: yume-chan/ya-webadb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yume-chan/ya-webadb] Run it as a server (#329)


Hi, thanks for amazing work! I have a usecase where I need to use it as a server. Is there some easy way we could support that?

**Comment by marospekarik** [comment]
Thanks for the hyperfast answer. I admit, my usecase is a bit odd. I'm having micro-computer connected to android device over adb and would like to have an interface for engaging with adb. I have a project where there will be a multiple people connecting to that device in order to trigger different pre-made shell scripts, file management and checking status of the device. I like the idea of using just browser for that kind of control instead of SSH. 

Thanks for the suggestion. I guess I'd need to write a server for that.

All best,
Maros

**Comment by yume-chan** [comment]
If you really want to use this library, I have the same suggestion as https://github.com/yume-chan/ya-webadb/issues/319#issuecomment-835404056

> [...], with https://github.com/thegecko/webusb, a drop-in replacement of browser's WebUSB API, I believe it's pretty easy to implement another backend for Node.js

Duplicating https://github.com/yume-chan/ya-webadb/blob/master/packages/adb-backend-webusb/src/backend.ts, modify it to use thegecko/webusb, then pass an instance to `Adb` constructor

https://github.com/yume-chan/ya-webadb/blob/1688296182f0bf8393ee98038c036aa7c38b0ef7/packages/demo/src/components/connect.tsx#L99
