### ISSUE TITLE
Periodic green screen on NVIDIA Shield Portable

### ISSUE THREAD

**Issue by guanzhangrtk** [yume-chan/ya-webadb#340]
First of all, cool project! I was looking for a web-based solution to connect to Android devices and came across this.

Currently I'm testing with an NVIDIA Shield Portable running Android 5.1 and for some reason periodically it would flash a green screen on scrcpy. I have tried the following encoders and both had the same issue:

```
OMX.Nvidia.h264.encoder
OMX.google.h264.encoder
```

This was tested on Chrome Version 91.0.4472.114 (Official Build) (x86_64) on macOS Big Sur 11.3.1. I also tested running scrcpy 1.18 locally and didn't encounter the issue.

Do you have any ideas what's causing the issue? Thanks!

**Comment by yume-chan** [comment]
Changing encoder requires stop and restart streaming, did you do that?

My guess is on the software H.264 decoder (tinyh264), it's less robust than FFMpeg used in native scrcpy. However I still don't think it had problem with `OMX.google.h264.encoder`.

**Comment by yume-chan** [comment]
If you have Chrome/Edge >= 94, now you can try the new WebCodecs decoder.

![image](https://user-images.githubusercontent.com/1330321/130576955-36b06d46-c3f6-4429-9ff3-a7fc367731c0.png)

It's a new Web standard that provides low-level video/audio decoding/encoding powered directly by browsers and can leverage hardware-acceleration. Comparing to TinyH264, it only uses half of CPU time but can deliver more FPS.

**Comment by yume-chan** [comment]
Now the WebCodecs decoder is used by default on supported browsers, so closing this. Please open a new issue if you have other questions.
