### ISSUE TITLE
connect to adb via wifi

### ISSUE THREAD

**Issue by namgk** [yume-chan/ya-webadb#345]
Is is possible to connect to adb over wifi? Currently the device has to be connected to the computer via usb right?

Thanks

**Comment by yume-chan** [comment]
See https://github.com/yume-chan/ya-webadb/discussions/245#discussioncomment-384030

**Comment by namgk** [comment]
Well, that’s not quite the way for real device, you’d need to “adb connect
deviceIp:5555” before you can do websockify thing.

This defeats the purpose of your repo as you need to have adb install in
your machine.

Ironically your repo, being a web based solution, can connect to the device
via serial but not via wifi :D

I’m imagining just to key in the device’s ip and port 5555 in your demo and
voila it just works.

Probably that’s far from reality? Or maybe somehow port the adb wifi
protocol over?

**Comment by yume-chan** [comment]
> 1. Web browsers can't open TCP sockets.
>
> _https://github.com/yume-chan/ya-webadb/discussions/245#discussioncomment-384030_

Unless browsers add support for [Raw Socket API](https://www.chromestatus.com/features/6398297361088512)

**Comment by yume-chan** [comment]
> Well, that’s not quite the way for real device, you’d need to “adb connect
> deviceIp:5555” before you can do websockify thing.

You can use this library to enable ADB over WiFi, no need for adb.

**Comment by namgk** [comment]
You misunderstood me about enabling adb over wifi, my point is, which you
had a valid answer about raw sockets on the browser, to do the equivalent
of "adb connect ipaddress:5555" command (assuming adb over wifi was already
enabled on the device).

It's not that I want to turn on the adb over wifi for the device, which
still requires a usb wire from the computer to it.

Anyway, seems like there's a hard technology limitation.
