### ISSUE TITLE
Webadb scrcpy solution for line adjustements

### ISSUE THREAD

**Issue by Alaingent** [yume-chan/ya-webadb#347]
Dear,

the web browser scrcpy solution is really a good idea, and webadb is really full options. BUT, please, could we change "resolution max", "refresh rate" etc...... like  in the desktop version of scrcpy on this browser version ? Because without these adjustment , for my computer and Edge browser it is too slow (because of high resolution not needed).

Thank you to explain me please where to put "line instruction" ?

Alain

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/143831762-3b6a5d6a-34ab-4915-8475-b59e4339ca0e.png)

My scrcpy implementation doesn't use command line arguments. You can adjust resolution and bitrate in the settings panel.

If you have Chrome > 94, you can also try the WebCodecs decoder which has much better performance.

**Comment by Alaingent** [comment]
Thank you BUT, like you will see on my EDGE brower updated (Version 96.0.1054.34) , i haven't any "Settings" button ? And i want to use only Edge because of all its features. And because now, Edge is Chromium compatible and Chrome store compatible, i think possible to have settings too in Edge no ? thanks a lot in advance.

![Capture web_29-11-2021_10539_app webadb com](https://user-images.githubusercontent.com/64490221/143838990-5a4bee0c-4a28-448e-8215-b4528931033d.jpeg)

**Comment by Alaingent** [comment]
Sorry i just understand, that YOUR webadb website is not one i used "https://app.webadb.com/#/". And since i used yours yume-chan etC... i have the "settings button" . But now strangely my mouse "right" button and my scroll "molette" are not fonctionnal ? have you a solution please ?

**Comment by yume-chan** [comment]
That's a fork of this project. I haven't add right click and scroll wheel support to scrcpy module, maybe they added it themselves. Since that one is close-sourced, nobody knows what they have changed.

Scroll  wheel support is on the plan, but I won't have time in near future to work on this project.

**Comment by Alaingent** [comment]
thank you i understand. have a nice end of year.
