### ISSUE TITLE
Help test the raw TCP wireless backend

### ISSUE THREAD

**Issue by yume-chan** [yume-chan/ya-webadb#349]
[Direct Sockets API](https://github.com/WICG/direct-sockets) (formerly, "raw sockets API") ([Chrome Platform Status](https://github.com/WICG/raw-sockets)) allows Web applications to create raw TCP or UDP sockets .

It has been implemented in Chrome for quite a while, but because the uncertainty and unsolved problems in the spec, it never been enabled.

To enable Direct Sockets API in a Chromium-based browser:

* Chromium before 98: add `--enable-features=DirectSockets` command line arguments.
* Chromium 98 and after: also add `--restricted-api-origins=https://www.example.com` to command line arguments, or set allowed origins from `chrome://flags/#restricted-api-origins`.  (replace `https://www.example.com` with real origin using the Direct Sockets API, to add multiple origins, separates them with comma)

It should be possible to create an ADB backend using this API to achieve plugin-free wireless connection.

**Comment by yume-chan** [comment]
To protect websites using Direct Sockets API being hijacked and creates unwanted sockets, Chrome requires the website to opt-in a more strict site isolation by returning the following HTTP response headers:

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

For detailed explanation, see [Why you need "cross-origin isolated" for powerful features](https://web.dev/why-coop-coep/).

**Comment by yume-chan** [comment]
Note: the requirement for enabling Direct Sockets API may change at any time. The spec itself may also get rejected.

**Comment by yume-chan** [comment]
The requirements have changed in mid-March (See https://github.com/WICG/direct-sockets/issues/35#issuecomment-1084082143)

The new steps are:

1. Lunch chrome with `--restricted-api-origins=https://ya-webadb-k2o0yviof-yume-chan.vercel.app` command line arguments (or adding `https://ya-webadb-k2o0yviof-yume-chan.vercel.app` to `chrome://flags/#restricted-api-origins`)
2. Open https://ya-webadb-k2o0yviof-yume-chan.vercel.app
3. Press "Menu -> More Tools -> Create Shortcut..."
4. Check "Open as window", Press "OK"
5. Close the new window
6. Open the app from Start/Launchpad/wherever your apps are

**Comment by ziyunfei** [comment]
Just FYI: restricted-api-origins has been renamed to isolated-app-origins.

**Comment by blackwiz4rd** [comment]
Hello all,
thanks for the great project,
after steps from comment:
- https://github.com/yume-chan/ya-webadb/issues/349#issuecomment-1084091053

I also don't see any Direct Sockets button.
Here is my version (google-chrome-stable arch linux)
`

Google Chrome | 109.0.5414.74 (Official Build) (64-bit)
-- | --
Revision | e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}
OS | Linux
JavaScript | V8 10.9.194.9

`

Any idea why?

**Comment by glitch128** [comment]
are you on the stable channel?

**Comment by blackwiz4rd** [comment]
> are you on the stable channel?

Yes, I be should: https://aur.archlinux.org/packages/google-chrome

**Comment by glitch128** [comment]
I have tried it on chromeOS stable 109, and it doesn't work. 
> The new steps only apply to Chrome Dev/Canary/Chromium versions after March 15th. I don't know if any Stable/Beta versions are shipped with this change. So also try the old steps.

**Comment by yume-chan** [comment]
The Direct Sockets spec changed dramatically in July last year. The new security model is fundamentally breaking many popular React framework and libraries, including some I'm using.

Also, Google Chrome haven't implemented WebUSB in the new model, so can't use both at the same time.

Closing this test as now. Will try to experiment again when the proposal is more mature.
