### ISSUE TITLE
Add device option missing

### ISSUE THREAD

**Issue by david-lev** [yume-chan/ya-webadb#350]
Hi, I was in the online demo a month ago Then there was an option to connect a device through web usb. Option that does not currently exist but is still supported in Chrome.
There is a site (app.webadb.com) that probably uses your code and it still allows the connection, is it a bug, or did you intentionally remove this option?
![Screenshot_20211214-212920_Chrome.jpg](https://user-images.githubusercontent.com/42866208/146066793-b32f08d9-63ae-4cfd-8db1-7a47298fb005.jpg)

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/146110232-a23b4eb9-a43c-46fa-8239-00300448d90d.png)

Click the left half.

**Comment by david-lev** [comment]
Thanks for fixing the problem!
