### ISSUE TITLE
demo run fail

### ISSUE THREAD

**Issue by alexlabs** [yume-chan/ya-webadb#351]
npm install will show as below:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@yume-chan%2fadb-backend-ws - Not found
npm ERR! 404 
npm ERR! 404  '@yume-chan/adb-backend-ws@^0.0.9' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'demo'

**Comment by yume-chan** [comment]
Please follow [CONTRIBUTE.md](https://github.com/yume-chan/ya-webadb/blob/master/CONTRIBUTE.md)

**Comment by alexlabs** [comment]
多谢，参考contribute.mk 问题已经解决
