### ISSUE TITLE
rush build demo error

### ISSUE THREAD

**Issue by yuxinxxgc** [yume-chan/ya-webadb#352]
![image](https://user-images.githubusercontent.com/4826982/147517717-bca4a4c0-e380-41d7-bdee-59dc47cd0ea0.png)

**Comment by yume-chan** [comment]
Never got this on Windows, macOS and GitHub CI running Ubuntu. Looks like a Next.js issue https://nextjs.org/docs/messages/failed-loading-swc

Please report to Next.js vercel/next.js#30468
