### ISSUE TITLE
Your browser does not support WebUSB standard, which is required for this site to work.

### ISSUE THREAD

**Issue by yuxinxxgc** [yume-chan/ya-webadb#353]
换成centos8后，rush build正常了，但是rush build:watch最后报一个ERROR: Cannot read property 'size' of undefined，在demo下npm run dev后，访问管理页面提示：Error
Your browser does not support WebUSB standard, which is required for this site to work.
但是浏览器访问 Online Demo的网址却一切正常，请问是什么原因？

**Comment by yume-chan** [comment]
> ERROR: Cannot read property 'size' of undefined

这个具体的输出长什么样？

> Your browser does not support WebUSB standard, which is required for this site to work.

WebUSB 需要 Secure Context，也就是 HTTPS 或者 localhost，如果你不是用 localhost 访问的，就要自己加证书，或者设置 chrome://flags/#unsafely-treat-insecure-origin-as-secure

**Comment by yuxinxxgc** [comment]
![image](https://user-images.githubusercontent.com/4826982/147622337-e774e050-73ba-4ff8-8dc1-035874084cf0.png)
就这样

**Comment by yume-chan** [comment]
找到个类似的 microsoft/rushstack#2845，不过没有结论

**Comment by yume-chan** [comment]
由于是外部工具问题，我会 close 这个 issue。

如果你有兴趣可以自行 debug 一下是哪里导致的并且给 rush 开个 issue，应该在 https://github.com/microsoft/rushstack/blob/da51af5e8ca424b7f9780a310a5934aced097db6/apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts 附近。
