### ISSUE TITLE
bu

### ISSUE THREAD

**Issue by upintheairsheep** [yume-chan/ya-webadb#354]
ADB backup is the only way to backup app data on Android without root or google drive. List of things:

Either specify an ID or do all.
The flags are checkmarks.

http://fileformats.archiveteam.org/wiki/Android_ADB_Backup

**Comment by upintheairsheep** [comment]
Checkmarks:
*Include System apps - checked by default, when unchecked, use the -nosystem flag
*Back up APK - backs up apk files via the -apk flag
*Back up photos, videos, and documents (Shared storage) - backs up shared storage via the -shared flag

advanced:

*Back up OBB - backs up OBB via -obb
*Include key value - includes key value via the -keyvalue tag

**Comment by upintheairsheep** [comment]
Also add ADB restore support too.

**Comment by yume-chan** [comment]
I have checked the source code, `adb backup` just calls `/system/bin/bu backup` with whatever parameter you give, then pipe the output into a file. I mean, it's not part of `adb` protocol, and writing binary wrappers like this is pretty useless.

So this request will be low priority.

**Comment by upintheairsheep** [comment]
also add support for browsing/extracting .ab files.

http://fileformats.archiveteam.org/wiki/Android_ADB_Backup

**Comment by upintheairsheep** [comment]
poggers its in development!

**Comment by upintheairsheep** [comment]
Can you actually start

**Comment by upintheairsheep** [comment]
closed but never started
