### ISSUE TITLE
Grant LogCat reader to read logs

### ISSUE THREAD

**Issue by upintheairsheep** [yume-chan/ya-webadb#369]
This will be very helpful for users that would love to view LogCat anywhere.

adb shell pm grant com.dp.logcatapp android.permission.READ_LOGS

To do the opposite

adb shell pm revoke com.dp.logcatapp android.permission.READ_LOGS

**Comment by yume-chan** [comment]
It won't add features for individual apps, especially when it can be easily done with the API (or the demo's terminal page).

You can create your own tool to add such shortcut, like what https://imxqd.xyz/activate/ and https://adb.miuies.com/ does
