### ISSUE TITLE
scrcpy landscape bug

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#372]
The scrcpy program only works in portrait mode. Whenever I put my tablet in landscape mode, the window becomes thin, and I can't see anything.

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/150724580-53f2dc11-de57-4e30-a1df-19e180cada73.png)

Can't reproduce.

Can you attach a screenshot and scrcpy log (in text)

![image](https://user-images.githubusercontent.com/1330321/150724667-41ccb20c-26af-4e6c-b4f3-3da08339d024.png)

**Comment by glitch128** [comment]
this is the screenshot
![Screenshot 2022-01-25 10 58 31 AM](https://user-images.githubusercontent.com/78228404/151041429-0008836d-911d-488d-bae9-64dead5660b1.png)
I am using ChromeOS to connect to a Samsung SM-T290 tablet. (Samsung Galaxy Tab A 2019)

**Comment by glitch128** [comment]
this it working fine in portrait mode
![image](https://user-images.githubusercontent.com/78228404/151042385-4318025a-70ec-4804-87e4-07ef13f12111.png)

**Comment by yume-chan** [comment]
Looks like you are using a forked version, not my original one.

Please try https://yume-chan.github.io/ya-webadb/ and copy-paste the scrcpy log in text form here.

**Comment by glitch128** [comment]
the official version is now saying this:
Server version: 1.21
Server arguments: log_level=debug,max_size=1080,bit_rate=4000000,max_fps=0,lock_video_orientation=-1,tunnel_forward=false,crop=,send_frame_meta=true,control=true,display_id=0,show_touches=false,stay_awake=true,codec_options=profile=8,level=16384,encoder_name=OMX.qcom.video.encoder.avc,power_off_on_close=false,clipboard_autosync=true
[server] DEBUG: Codec option set: profile (Integer) = 8
[server] DEBUG: Codec option set: level (Integer) = 16384
[server] DEBUG: Creating encoder by name: 'OMX.qcom.video.encoder.avc'
stack corruption detected (-fstack-protector)
Aborted 
now it won't even start

**Comment by glitch128** [comment]
I have a feeling that the stack corruption is the problem.

**Comment by yume-chan** [comment]
No, the stack corruption is a new issue in 1.21 Genymobile/scrcpy#2841 caused by a bug in Samsung custom ROM. I haven't decided how to workaround it.

Please try a different encoder. Hit start, ignore the error, open the settings panel, choose another encoder.

**Comment by yume-chan** [comment]
I pushed a workaround for the stack corruption problem 24a5a58609a3629aee70163c6da1b3a0265eb586

**Comment by glitch128** [comment]
ok, its working now
