### ISSUE TITLE
App management

### ISSUE THREAD

**Issue by yume-chan** [yume-chan/ya-webadb#373]
- [x] Enumrate installed apps
  - [ ] ~icon,~ name, package name, version, target api, arch
  - [ ] permission
  - ❓ size
- [ ] Install app
  - [x] apk
    - [x] legacy mode
      - [x] normal push
      - ~~[ ] fast deploy~~
    - [x] stream mode
      - [x] normal stream
      - ~~[ ] fast deploy~~
      - [x] `cmd package`
  - ❓  aab
  - ❓ apkm (by apkmirror)
  - ❓ xapk (by apkpure)
- [x] Uninstall app
  - [x] `pm`
  - [x] `cmd package`
- [x] Launch app/activities (`am`) #366
- [x] Backup/restore individual app data (`bu`) #354
- [ ] Demo

Fast deploy first pushes and runs a helper app on device. For native ADB the helper app is embedded in the binary file as a resource. It's always hard to build Android components due to the resource usage, so it won't be supported.

**Comment by upintheairsheep** [comment]
and apk extraction of an app.

**Comment by upintheairsheep** [comment]
Add a function to browse app files, for rooted devices it does normal stuff , in debuggable apps it does https://android.stackexchange.com/questions/48609/how-can-i-access-the-files-in-data-data-and-copy-them-into-memory-card-withou/50411 commands and there is a storage emulated 0 Android data packageid folder browser

**Comment by upintheairsheep** [comment]
And

**Comment by yume-chan** [comment]
Updates

* It should be impossible to get app icons using only ADB commands. A Java package similar to Scrcpy is required to call Android framework APIs to generate the icon. Using APIs also greatly simplify parsing the results. But it's kind of out of scope for this project, so won't be supported.
* Similar story for `am`. I have some strange error like `Error: Activity not started, unable to resolve Intent` when using `am` to launch the main activity of apps, while `monkey` works. So it's better to use the same API as `monkey` to resolve the main activity component name beforehand, than using `action.MAIN` and `category.LAUNCHER` directly. This also requires Java code so won't be supported. (I need `am` parameters like `--display` so using `monkey` is also not an option)

**Comment by yume-chan** [comment]
> Similar story for am. I have some strange error like Error: Activity not started, unable to resolve Intent when using am to launch the main activity of apps.

A workaround is first resolving the activity using `pm resolve-activity` (`PackageManager#resolveActivity`) then `am start` (`ActivityManager#startActivity`).

---

All main goals are completed, other stretch goals will be investigated when required.
