### ISSUE TITLE
aspect ratio or resolution change

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#378]
**Describe the solution you'd like**
I would like it if you could change the aspect ratio of your device from a menu on the website.

**Describe alternatives you've considered**
I have tried using the interactive shell in the website to change the aspect ratio, but it doesn't work.

**Comment by yume-chan** [comment]
How can you change the aspect ratio or resolution using ADB?

**Comment by yume-chan** [comment]
`wm size 800x1280` works on my device.

If it worked in native ADB, it will work in interactive shell, they are the same thing.

**Comment by glitch128** [comment]
I get this message in the interactive shell
![image](https://user-images.githubusercontent.com/78228404/154535058-5c463eb5-ba02-4704-9429-a33b7469144a.png)

**Comment by yume-chan** [comment]
Don't prepend with `adb shell`

**Comment by glitch128** [comment]
thank you
