### ISSUE TITLE
Error selecting WebCodecs to start service

### ISSUE THREAD

**Issue by sbfkcel** [yume-chan/ya-webadb#379]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb

### Runtime

macOS 10.15.7 chrome 98

### Device

Redmi8，Android 9

### Describe the bug

Error selecting WebCodecs to start the service. And TinyH264 everything works fine.

From the log, the service failed to start, like a parameter error

### Steps to reproduce

![Snipaste_2022-02-16_10-10-29](https://user-images.githubusercontent.com/5469785/154183640-899ea96a-34dd-4a3f-8ea8-d400a78157a7.png)

**Comment by yume-chan** [comment]
WebCodecs decoder requests High 5.1 profile and TinyH264 decoder requests Baseline 4.

I suspect your device doesn't support such a "high" configuration, so I pushed a change to use devices' default setting. Please try again.

**Comment by sbfkcel** [comment]
Cool, it looks real. Try again, it's normal.

**Comment by yume-chan** [comment]
Thanks for verify, close as fixed.
