### ISSUE TITLE
store setting's values

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#384]
**Is your feature request related to a problem? Please describe.**
I would like it if it would keep the scrcpy settings from the previous reload. Its tedious when I have to keep adjusting the max resolution and bitrate.

**Describe the solution you'd like**
use cookies or something to store the values across reloads and closes.

**Comment by glitch128** [comment]
hey, quick question. I'm guessing it is, but is the setting saving automatically stored?

**Comment by yume-chan** [comment]
Yes, the settings are saved when Scrcpy successfully started, and loaded when device connected.

It's stored on device, so each device can have different settings, and connect the device to different computers will always use the same settings.

**Comment by glitch128** [comment]
oh, ok.
