### ISSUE TITLE
[Authentication Required] How to connect to a device that requires secondary authentication?

### ISSUE THREAD

**Issue by VincentLin94** [yume-chan/ya-webadb#390]
- **Unable to connect to a device that requires passwd**

  - During exploring the demo website, I found that some devices require secondary authentication to proceed(eg. enter passwd).
  - ![image](https://user-images.githubusercontent.com/49602729/160373473-f2ff4df2-c889-4f95-b8ec-c4b3aeadbc21.png)

- **Is it possible to get through with this?**

  - I haven't been able to find a way to enter the passwd manually or pre-enter one in my code.
  - As I'm not so familiar with the webUSB APIs, I'm anxious to find out whether it's viable or not :)

**Comment by yume-chan** [comment]
1. What's the brand and model of your device?
2. How do you use official adb with your device? Can you share a complete log?

**Comment by VincentLin94** [comment]
> 1. What's the brand and model of your device?
> 2. How do you use official adb with your device? Can you share a complete log?

Thx for ur kindly reply :)

1. Its an unix-based, embedded smart device we developed. As so, the adb protocol interated in this device is not the original one but a portable version.
2. Normally, we need the local interactive terminal to enter the passwd. But obviously we cannot initialize an interactive shell without the authentication. Therefore, I'm afraid there is not much log info to share.

Additionally, is it possible to achieve an interactive shell using merely JS instead of TS?

**Comment by yume-chan** [comment]
Without further information I can't provide any more help.

> Additionally, is it possible to achieve an interactive shell using merely JS instead of TS?

Yes, most packages have been published to NPM, so you can create your own projects using them.

**Comment by yume-chan** [comment]
Close as stale.
