### ISSUE TITLE
"Offset is outside the bounds of the DataView" error

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#395]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb

### Runtime

Chrome OS, 100 (stable)

### Device

(unknown, 4) (SM-T290, 11)

### Describe the bug

I tried to connect to my 4.0 tablet, and it gave me the "Offset is outside the bounds of the DataView" error, and now it is giving me the same error on my android 11 Samsung tablet.

### Steps to reproduce

1. connect to android 4.0.
2. get the error.
3. connect to android 11.
4.  get the error.

**Comment by glitch128** [comment]
Is there a way to fix this?

**Comment by glitch128** [comment]
help?

**Comment by yume-chan** [comment]
When did that happen? Just after clicking the "Connect" buttons?

**Comment by glitch128** [comment]
yes

**Comment by adnanaga** [comment]
Yea this is happening to me too

**Comment by yume-chan** [comment]
@glitch128 @adnanaga What's your Operating System?

**Comment by adnanaga** [comment]
OSX Monterey 12.3

**Comment by yume-chan** [comment]
My code takes advantage of a bug in Chrome's WebUSB implementation on Windows. This will take some time to fix.

**Comment by glitch128** [comment]
> @glitch128 @adnanaga What's your Operating System?

Chrome OS

**Comment by litten2up** [comment]
me too tho it looks like it can't find manifest.json
![image](https://user-images.githubusercontent.com/55027142/162269117-acd0c71b-5549-4105-89b3-6b5618eb7d3c.png)

**Comment by glitch128** [comment]
wait, does this mean that this will work with my android 4.0?

**Comment by yume-chan** [comment]
I don't have Android 4.0 devices to test on, but I have seen it working on Android 5.1 and 6.0, so there is no reason for it to not work on 4.0.
