### ISSUE TITLE
super speed scrolling w/ touchpad on scrcpy

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#396]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb

### Runtime

Chrome OS, 99 (stable)

### Device

(SM-T290, 11)

### Describe the bug

the title says it all. when I scroll with a touchpad on scrcpy, it goes really fast.
that's all, also kind of an inconvenience 

### Steps to reproduce

1. scroll

**Comment by yume-chan** [comment]
Fixed in 076d67e2102ff587be946d34cf67e637a30e2542
