### ISSUE TITLE
spawn/spawnAndWait fails to open socket

### ISSUE THREAD

**Issue by stylesuxx** [yume-chan/ya-webadb#405]
### Issue Checklist

- [X] I'm using the library programmatically

### Library version

0.0.13

### Runtime

Linux, Chrome Version 100.0.4896.127 (Official Build) (64-bit)

### Device

DJI FPV goggles V2

### Describe the bug

When trying to spawn a process:

```javascript
const device = await AdbWebUsbBackend.requestDevice();
const streams = await device.connect();
const adb = await Adb.authenticate(streams, credentialStore, undefined);
const result = await adb.subprocess.spawnAndWait(["ls"]);
```

I get the following error (same thing with `spawn` and `spawnAndWaitLegacy`):
```
Error: Socket open failed
    at AdbPacketDispatcher.handleClose (dispatcher.ts:129:1)
    at Object.write (dispatcher.ts:67:1)
    at g (webidl.ts:78:1)
    at S (webidl.ts:88:1)
    at Object.write (underlying-sink.ts:71:1)
    at WritableStreamDefaultController.i [as _writeAlgorithm] (writable-stream.ts:1114:1)
    at writable-stream.ts:544:1
    at Br (writable-stream.ts:1202:1)
    at writable-stream.ts:1171:1
    at Cr (writable-stream.ts:917:1)
    at Object._chunkSteps (pipe.ts:117:1)
    at G (default-reader.ts:51:1)
    at at (default-controller.ts:251:1)
    at ReadableStreamDefaultController.enqueue (default-controller.ts:91:1)
    at Object.pull (transform.ts:345:1)
```
This seems to be specific on my device, I tried with a phone and it works. Interestingly enough I can get a shell process no problem:

```javascript
const device = await AdbWebUsbBackend.requestDevice();
const streams = await device.connect();
const adb = await Adb.authenticate(streams, credentialStore, undefined);
const socket = await adb.subprocess.shell();
const writer = socket.stdin.getWriter();
socket.stdout.pipeTo(new WritableStream({
  write: (chunk) => {
    console.log(decodeUtf8(chunk));
  }
}));
```

I would really love to be able to spawn a process though and get output and exit codes. Let me know which information you need to further debug this

### Steps to reproduce

```javascript
const device = await AdbWebUsbBackend.requestDevice();
const streams = await device.connect();
const adb = await Adb.authenticate(streams, credentialStore, undefined);
const result = await adb.subprocess.spawnAndWait(["ls"]);
```

**Comment by yume-chan** [comment]
I checked ADB source code and `spawn` should never return this error, maybe it was modified by the manufacturer to disable this feature.

Do you know its Android version? Does it work with native ADB (`adb shell ls`)?

**Comment by stylesuxx** [comment]
With native ABD `adb shell ls` it is not a problem, output as expected:

```
➜  web-app git:(master) ✗ adb shell ls /opt/
bin
etc
fonts
home
lib
root
sbin
share
tmp
usr
var
```

```
root@XXXX:/ # getprop ro.build.version.release 
6.0
root@XXXX:/ # getprop ro.build.version.sdk                     
23
```

**Comment by yume-chan** [comment]
You ran `adb shell ls /opt` vs. `adb.subprocess.spawnAndWait(["ls"])`, they are different.

Can you try `adb shell ls` or `adb.subprocess.spawnAndWait(["ls", "/opt"])`?

**Comment by yume-chan** [comment]
Version 0.0.14 released with the fix.
