### ISSUE TITLE
auto connect for web demo

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#406]
**Is your feature request related to a problem? Please describe.**
when I accept the `allow access to tablet data` it disconnects from the website.

**Describe the solution you'd like**
I would like an option to allow automatic connecting to previously paired devices

**Comment by yume-chan** [comment]
Did you see an error popup after switching to file transfer mode on device?

![image](https://user-images.githubusercontent.com/1330321/166108115-8b8ae915-4b94-4dfe-92da-e121a0decaae.png)

**Comment by glitch128** [comment]
> Did you see an error popup after switching to file transfer mode on device?
> 
> ![image](https://user-images.githubusercontent.com/1330321/166108115-8b8ae915-4b94-4dfe-92da-e121a0decaae.png)

no, its just that when I accept the `allow access to tablet data` prompt, on scrcpy, it dissconnects, and I have to reconnect it.

**Comment by yume-chan** [comment]
How does the `allow access to tablet data` prompt look like?

**Comment by glitch128** [comment]
it looks like this, and when I press allow, then the error pops up
![image](https://user-images.githubusercontent.com/78228404/166987932-980bae61-07b9-4ebf-8426-8d342abc820f.png)

**Comment by yume-chan** [comment]
It looks like a normal USB configuration switching prompt, however, in my testing, these disconnections always result in a generic WebUSB error that's indistinguishable from other transferring errors.

Maybe there is an issue in Chrome's implementation or the WebUSB spec itself, but I have been very busy recently and had no time to investigate more.

**Comment by yume-chan** [comment]
Upstream issue filed:

* WICG/webusb#219

**Comment by yume-chan** [comment]
Added in the new app.

See #576
