### ISSUE TITLE
Allow input for scrcpy arguments

### ISSUE THREAD

**Issue by LordGiacomoS** [yume-chan/ya-webadb#409]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way that I can find to perform scrcpy arguments through the basic web application, as the interactive shell automatically adds `adb shell` at the beginning of every input, and there are no other places in the app that would allow for modifying scrcpy settings beyond the limited settings menu in the scrcpy tab.

**Describe the solution you'd like**
Ideally, there would be some console in which scrcpy arguments could be run, either as an addition to the interactive console or a seperate tab.

**Describe alternatives you've considered**
Potentially, you could just add the ability to modify a few more settings in the existing scrcpy settings menu (for instance I am trying to do something that requires `scrcpy --rotation` and `scrcpy --display`), but ideally, there would be some way to do manage configuration options that are possible via WebUSB (obviously arguments like `scrcpy --window-borderless` might not be viable since they would do nothing at best), since there other useful scrcpy arguments that I can see people wanting to use (i.e. `scrcpy --crop`, `scrcpy --lock-video-orientation`, and potentially some of the window resizing arguments).

**Comment by yume-chan** [comment]
Like #367, this library provides an API for developers to use in their applications. Re-implementing command line arguments on top of this library is possible but not a goal of itself.

The setting panel is being reworked and more options will be added. I will priorities the ones you have mentioned.

- [ ] `display`
- [ ] `crop`
- [ ] `lock-video-orientation`

`--rotation` is also done by the client, but sounds easy to add.
