### ISSUE TITLE
spawnAndWait exitCode always 0 even if command fails

### ISSUE THREAD

**Issue by stylesuxx** [yume-chan/ya-webadb#412]
### Issue Checklist

- [X] I'm using the library programmatically

### Library version

0.0.15

### Runtime

Linux, Chrome Version 100.0.4896.127 (Official Build) (64-bit)

### Device

DJI FPV goggles V2

### Describe the bug

`spawnAndWait` always seems to return an exitCode of 0, no matter the actual outcome:

```javascript
const output = await adb.subprocess.spawnAndWait(["test", "-f", "/non/existent/path"]);
```

output:
```json
{
    "stdout": "",
    "stderr": "",
    "exitCode": 0
}
```

Also `stderr` is not populated, instead the output can be found in `stdout`.

In the CLI the same command yields exitCode 1:

```
root@XXX:/ # test -f /non/existent/path
root@XXX:/ # echo $?
1
```

### Steps to reproduce

```javascript
const output = await adb.subprocess.spawnAndWait(["test", "-f", "/non/existent/path"]);
```

**Comment by yume-chan** [comment]
Returning exit code from ADB requires Android 7 (Shell Protocol or `shell_v2` feature). 

Maybe you can do something like `spawnAndWait(["test", "-f", "/non/existent/path", ";echo $?"])` and parse it yourself (basically make your own shell protocol).  ADB daemon runs the given command using `sh -c` so scripts should also be acceptable.

Note that the array of parameters is joined to a string before sending to device, it's only for helping you format your code.

**Comment by stylesuxx** [comment]
OK, thank you - that's basically what I did as a workaround right now.
I assume this does not only apply to exit codes, but also to `stderr` - right?

**Comment by yume-chan** [comment]
Correct.

https://github.com/yume-chan/ya-webadb/blob/4d01f25124a812a406dfa690bd69edb1dbf3f9b3/libraries/adb/src/commands/subprocess/protocols/none.ts#L6-L14

https://github.com/yume-chan/ya-webadb/blob/4d01f25124a812a406dfa690bd69edb1dbf3f9b3/libraries/adb/src/commands/subprocess/protocols/shell.ts#L95-L103

**Comment by stylesuxx** [comment]
Thank you. Closing this.
