### ISSUE TITLE
[demo]auto change screen ratio when connecting to scrcpy

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#417]
**Describe the solution you'd like**
A setting to automatically use the `wm size` ADB command to change the screen ratio to fit the screen connecting to it and change back to the original screen ratio when disconnecting.
The screen size to change to would be the ratio of the monitor.
**Describe alternatives you've considered**
I have used the ADB command to change my screen size, but the loss of useable screen space makes it feel a bit cramped.

**Comment by yume-chan** [comment]
Just saw Genymobile/scrcpy#3265, looks like `wm size` doesn't work well on some devices.

**Comment by yume-chan** [comment]
Link some upstream issues: Genymobile/scrcpy#3207, Genymobile/scrcpy#3419

**Comment by glitch128** [comment]
this was related to #378 and has been better implemented by Virtual Extended Display in the new web app.
