### ISSUE TITLE
Connect to/create external monitor by default

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#421]
**Describe the solution you'd like**
I would want an option to make scrcpy connect to an external monitor, and if there's not one available, create one with previous user input, and then connect to that monitor.

**Describe alternatives you've considered**
I have been connecting to my device, pressing refresh, and then going to the eternal monitor and connecting to it, but I have to do it very fast because it will not connect to it if I'm not fast or if I disconnect and try to reconnect. this is also building on my other request #384 with keeping values across closes and reloads.

**Comment by yume-chan** [comment]
Generally, I won't add features to my Scrcpy client outside the original implementation. I would recommend you first sending feature requests to [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy) (together with #417).

**Comment by yume-chan** [comment]
I have found a method to create virtual displays from Scrcpy (https://github.com/Genymobile/scrcpy/issues/1887#issuecomment-1405184608). Please subscribe to that issue for updates.
