### ISSUE TITLE
The demo Logcat output is diffrent from the real logcat output 

### ISSUE THREAD

**Issue by alexlabs** [yume-chan/ya-webadb#424]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb

### Runtime

MacOS Chrome 已是最新版本 版本 102.0.5005.61（正式版本） (arm64)

### Device

Android 12

### Describe the bug

The logcat output is : 
CamX    : [ERROR][META   ] camxhal3metadatautil.cpp:1172 UpdateMetadata() Cannot set Metadata for Tag: 0x10032
the Demo output is : 
CamX[ERROR][META ] camxhal3metadatautil.cpp:1172 UpdateMetadata() Cannot set Metadata for Tag: 0x10032 

### Steps to reproduce

as above discription

**Comment by alexlabs** [comment]
I mean that the tab/ : /space chars are missing

**Comment by yume-chan** [comment]
The logcat view is not done yet (and I don't have time to finish it). But the tag is now separated from the message.
