### ISSUE TITLE
Sudden dissaperence of issues

### ISSUE THREAD

**Issue by upintheairsheep2** [yume-chan/ya-webadb#426]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb

### Runtime

Na

### Device

Na

### Describe the bug

Sorry for my sudden dissaperence yume chan. My account got privated by GitHub because it toght I was a spam bot. The support of GitHub is the worst in the world and not responding to me.

### Steps to reproduce

1.
2.
3.
Na

**Comment by yume-chan** [comment]
Welcome back! 

Sadly those issues won't come back. You can re-create them if they are still relevant, and you still remember them. Just to be noted that I'm pretty busy now so won't have time to work on them anytime soon.

**Comment by upintheairsheep** [comment]
Github finally unflagged me!
