### ISSUE TITLE
About Turn screen off

### ISSUE THREAD

**Issue by FeranyDev** [yume-chan/ya-webadb#428]
**Is your feature request related to a problem? Please describe.**
When I was using Web Scrcpy, I found that my phone's screen was always on, which was a huge power drain. But when I manually turn off the screen I find that the Web Scrcpy display also goes black.

**Describe the solution you'd like**
I would like to have a feature that turns off the phone screen but the Web Scrcpy does not go off at the same time.

**Describe alternatives you've considered**
While I was browsing the Scrcpy project, I found that Scrcpy does provide this feature (https://github.com/Genymobile/scrcpy#turn-screen-off). I hope ya-webadb will implement this feature as well, thanks a lot.

**Additional context**
![image](https://user-images.githubusercontent.com/43532576/175241824-01124e66-3993-490c-b7e1-d001b46dfd08.png)

**Comment by yume-chan** [comment]
This is a small change, but it need to wait until #427 is done.
