### ISSUE TITLE
Failed to execute 'transferIn' on 'USBDevice': A transfer error has occurred.

### ISSUE THREAD

**Issue by stylesuxx** [yume-chan/ya-webadb#433]
### Issue Checklist

- [X] I'm using the library programmatically

### Library version

0.0.15

### Runtime

Linux, Chrome Version 100.0.4896.127 (Official Build) (64-bit)

### Device

DJI FPV goggles V2

### Describe the bug

From time to time this error gets thrown, I checked the code, it seems to be a [known issue](https://github.com/yume-chan/ya-webadb/blob/6b76f344c8b588f4a1485215dcc83e0a44c1480f/libraries/adb-backend-webusb/src/backend.ts#L61).

I can see this happening on Chrome and Edge on Windows 10. I can't reproduce it on my Linux machine though.

Is there any information I might help you out with?

### Steps to reproduce

1. This seems to occur when a device is being disconnected.

**Comment by yume-chan** [comment]
> it seems to be a [known issue](https://github.com/yume-chan/ya-webadb/blob/6b76f344c8b588f4a1485215dcc83e0a44c1480f/libraries/adb-backend-webusb/src/backend.ts#L61).

Yes, WebUSB spec didn't define what should happen when device disconnects, and Chrome implemented as firing a generic transfering error.

See:

* #406
* WICG/webusb#219

Maybe other errors are so rare that you can always handle this error as device disconnected, but I decided to leave it as is and let the consumers decide.
