### ISSUE TITLE
main分支中的demo无法启动开发环境

### ISSUE THREAD

**Issue by FickXu** [yume-chan/ya-webadb#443]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb

### Runtime

win11  chrome104

### Device

window 系统

### Describe the bug

![image](https://user-images.githubusercontent.com/7928985/187616442-fbb4294f-a118-4046-b9fb-35b44f89bece.png)
![image](https://user-images.githubusercontent.com/7928985/187617707-cfbbd671-59d7-4b70-a6d6-da92686aa850.png)

### Steps to reproduce

你好作者，我下载了项目并尝试启动项目，但遇到了一些问题，希望得到你的帮助。
1.下载了main分支和tag0.0.16两个版本，基础demo目录
2.运行npm install  报错，这几个依赖因为没有正式发布报错。依赖：
![image](https://user-images.githubusercontent.com/7928985/187616442-fbb4294f-a118-4046-b9fb-35b44f89bece.png)
3.在pagejson.js中移除了对应的6个包。执行npm install正常安装了其他依赖，此时项目无法正常启动
4.我将libraries中对应的包复制到node_modules中或者demo目录下，修改代码中对应的引用路径。但提示‘Module not found: Can't resolve xxx’，似乎不是一个正确的模块
请问我需要怎么处理才能让项目正常启动？

**Comment by yume-chan** [comment]
See https://github.com/yume-chan/ya-webadb/blob/main/CONTRIBUTING.md

**Comment by FickXu** [comment]
非常感谢你的指引，现在开发环境已经可以正常启动了。不过有些新情况不是很了解，希望你能帮助解答。
1.运行rush update
![image](https://user-images.githubusercontent.com/7928985/187643161-9a5397e4-c3a6-4b5c-9665-c9fa3e68a6bb.png)
2.运行rush build:watch
![image](https://user-images.githubusercontent.com/7928985/187643716-60477108-fef0-4a42-8c43-468ebf10673c.png)
它们不影响开发环境运行，只是我还想了解下是什么原因导致终端中显示的异常。非常感谢！

**Comment by yume-chan** [comment]
1. Currently Docusaurus is not being used, so you can safely ignore that dependency error.
2. Rush only works inside of a Git repository. Clone this repo with Git.

**Comment by FickXu** [comment]
谢谢你的解答，非常感谢！
