### ISSUE TITLE
fastboot protocol should be easy to implement

### ISSUE THREAD

**Issue by Zibri** [yume-chan/ya-webadb#452]
adding fastboot protocol would be nice..
I made some tests and webusb supports both fastboot both qualcomm qdload and diag...

**Comment by yume-chan** [comment]
Duplicate of #343

I don't have BL unlocked devices so I can't test and implement that, but I will accept community contributions.

**Comment by Zibri** [comment]
> Duplicate of #343
> 
> I don't have BL unlocked devices so I can't test and implement that, but I will accept community contributions.

https://kdrag0n.github.io/fastboot.js/demo/

https://kdrag0n.github.io/fastboot.js

no need to be unlocked to use fastboot...
