### ISSUE TITLE
Not all packages on NPM

### ISSUE THREAD

**Issue by JanCraft** [yume-chan/ya-webadb#454]
### Issue Checklist

- [X] I'm using the library programmatically

### Library version

0.0.16

### Runtime

macOS 12.6 on M1 chip, Chrome 105

### Device

Pixel 6, Android 13

### Describe the bug

I tried to build the demo, but it told me it couldn't find some packages. I checked and they aren't on NPM.
I tried using the `npm link` command but it still ended up having errors with packages.

Could you please upload the `stream-extra`, `adb-backend-webusb`, `b-tree` and `scrcpy-decoder-webcodecs` packages to NPM?

### Steps to reproduce

1. Clone the repo
2. Try running `npm install`
3. Even try linking each local package using `npm link`, it will still error out

**Comment by yume-chan** [comment]
Please read https://github.com/yume-chan/ya-webadb/blob/main/CONTRIBUTING.md
