### ISSUE TITLE
Compiler library from tsc failed

### ISSUE THREAD

**Issue by alexk1028** [yume-chan/ya-webadb#462]
### Issue Checklist

- [x] I'm using the library programmatically

### Library version

0.016

### Runtime

windows 10.1 typescript 4.1.6

### Device

MIUI android 12

### Describe the bug

[error.log](https://github.com/yume-chan/ya-webadb/files/9942756/error.log)

### Steps to reproduce

1. run `npm install` 
2.run `tsc`
[tsconfig.txt](https://github.com/yume-chan/ya-webadb/files/9942758/tsconfig.txt)
[package.txt](https://github.com/yume-chan/ya-webadb/files/9942759/package.txt)

**Comment by yume-chan** [comment]
It requires a recent version of TypeScript.

**Comment by alexk1028** [comment]
> It requires a recent version of TypeScript.

thanks. it works
