### ISSUE TITLE
Capture/record screen using scrcpy

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [yume-chan/ya-webadb#465]
Is it possible to capture video stream to blob in the browser and save it as file?

**Comment by yume-chan** [comment]
Are you asking how to do this when using my package or requesting such feature in the demo website?

**Comment by FluorescentHallucinogen** [comment]
My question was, is it technically possible? And yes, it would be great to have that feature right in the demo.

**Comment by FluorescentHallucinogen** [comment]
BTW, why you are using `<canvas>` element to render the video instead of the `<video>` element?

**Comment by FluorescentHallucinogen** [comment]
Something like:

```html
<a href='#' id="link" download="video.webm">Download</a>

<script>
  link.href = URL.createObjectURL(blob);
</script>
```

**Comment by yume-chan** [comment]
> why you are using <canvas> element to render the video instead of the <video> element?

Because Scrcpy gives a raw H.264 stream which is not playable by `<video>`

> `link.href = URL.createObjectURL(blob);`

Same reason, this won' work.

**Comment by yume-chan** [comment]
> is it technically possible

It's technically possible, but hard to do. Video encoding and container are super complex.

**Comment by Zibri** [comment]
@yume-chan not difficult at all:

Here is an example for recording 5 seconds of video from a canvas.
```
var canvas = document.querySelector("canvas");
var ctx = canvas.getContext("2d");

var video = document.querySelector("video");

var colors = ["red", "blue", "yellow", "orange", "black", "white", "green"];
function draw (){
	ctx.fillStyle = colors[Math.floor(Math.random() * colors.length)];
  ctx.fillRect(0, 0, canvas.width, canvas.height);
}
draw();

var videoStream = canvas.captureStream(30);
var mediaRecorder = new MediaRecorder(videoStream);

var chunks = [];
mediaRecorder.ondataavailable = function(e) {
  chunks.push(e.data);
};

mediaRecorder.onstop = function(e) {
  var blob = new Blob(chunks, { 'type' : 'video/mp4' });
  chunks = [];
  var videoURL = URL.createObjectURL(blob);
  video.src = videoURL;
};
mediaRecorder.ondataavailable = function(e) {
  chunks.push(e.data);
};

mediaRecorder.start();
setInterval(draw, 300);
setTimeout(function (){ mediaRecorder.stop(); }, 5000);
```

**Comment by Zibri** [comment]
Here is your full function:

```
function Recorder(canvas) {

    var ctx = canvas.getContext("2d");

    var videoStream = canvas.captureStream(30);
    var mediaRecorder = new MediaRecorder(videoStream);

    var videoURL;

    var chunks = [];
    mediaRecorder.ondataavailable = function(e) {
        chunks.push(e.data);
    }

    function download(dataurl, filename) {
        const link = document.createElement("a");
        link.href = dataurl;
        link.download = filename;
        link.click();
    }

    mediaRecorder.onstop = function(e) {
        var blob = new Blob(chunks,{
            'type': 'video/mp4'
        });
        chunks = [];
        videoURL = URL.createObjectURL(blob);
    }

    mediaRecorder.ondataavailable = function(e) {
        chunks.push(e.data);
    }

    this.start = ()=>mediaRecorder.start();
    this.stop = ()=>mediaRecorder.stop();
    this.pause = ()=>mediaRecorder.pause();
    this.resume = ()=>mediaRecorder.resume();
    this.url = ()=>videoURL;
    this.download = (fileName)=>{
        if (videoURL != "")
            download(videoURL, fileName)
    }
}

```
To use it:

rec = new Recorder(yourcanvaselement);

then:
**rec.start()**
rec.pause()
rec.resume()
**rec.stop()**
**rec.download("filename.mp4")** /// or any name.mp4
to get the recording URL without downloading:
**rec.url()**

**Comment by yume-chan** [comment]
Did some research on `MediaRecorder`:

1. both Chrome and Firefox support webm container, which, as a subset of mkv, is suitable for recording live streams.
2. Chrome supports avc1 codec but Firefox doesn't, this can affect compatibility.
3. `MediaRecoder` can stream the output, so I can pipe it into StreamSaver.
4. `MediaRecorder` introduces an extra encoding process, it will waste a bunch of CPU and RAM. But it's easier than implementing a re-muxer. It's a trade-off.
5. Looks like `MediaRecoder` supports variable frame rate by manually feed frames into it, however the timestamp will not be even near precise, and there is no way to include skipped frames.
6. Looks like `MediaRecoder` also supports changing video size at any time. Requires further testing.

**Comment by Zibri** [comment]
@yume-chan 
why did you close this???
I sent you the code and it works perfectly on the web page...!!! and saves MP4

**Comment by yume-chan** [comment]
It's still open

**Comment by yume-chan** [comment]
> and saves MP4

It doesn't. Chrome doesn't support exporting mp4. Also, mp4 is a bad format for recording live stream, because it requires updating metadata on finish, otherwise the whole file is un-playable.
