### ISSUE TITLE
Root access in File Manager 

### ISSUE THREAD

**Issue by mattwakeman** [yume-chan/ya-webadb#466]
Some devices enable root access to the file system. E.g is a device that contains the Su binary or is of type user-debug 

It would be really handy to have a button in file manager which allows for navigation, uploaded and download of files in directories only available if the device is accessed with root.

**Comment by yume-chan** [comment]
I don't have a rooted device. Does `adb root` still work on modern devices?

**Comment by upintheairsheep** [comment]
It works on careless manufacturers who use AOSP and don’t bother to turn it
off. Tested on Jadoo7 with Android Pie

**Comment by mattwakeman** [comment]
Implemented a local hack to achieve my goals.
