### ISSUE TITLE
More than one device/emulator

### ISSUE THREAD

**Issue by pezzeonline** [yume-chan/ya-webadb#477]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb

### Runtime

macOS 13.0.1

### Device

Alcatel 1, Doogee X95

### Describe the bug

When I connect to a phone in websocket everything works fine except scrcpy that returns everytime `more than one device/emulator`.

### Steps to reproduce

1. Set adb in tcp mode `adb tcp 5555`
2. Crate a websockify tunnel `node ./websockify.js 15555 192.168.42.160:5555`
3. Connect to phone using Websocket `ws://localhost:15555`
4. Check everything related to adb is working correctly (file manager, screen capture, logcat, etc...)
5. Try to use scrcpy and get the error

**Comment by pezzeonline** [comment]
Scrcpy is working on Redmi 9

**Comment by yume-chan** [comment]
When devices with Android version <9 is connected wirelessly, "Use forward connection" option must be enabled for Scrcpy to work. 

It's a bug in ADB itself, see https://github.com/Genymobile/scrcpy/issues/5.

![image](https://user-images.githubusercontent.com/1330321/213141107-0cc0a2ff-6771-49c8-af68-188d4c4e34d9.png)

![image](https://user-images.githubusercontent.com/1330321/213141172-017d244b-1e36-4363-b3ba-60685d918646.png)

**Comment by pezzeonline** [comment]
You're great!

**Comment by yume-chan** [comment]
Can you do me a favor. I want to detect this error and enable forward connection automatically (like the native Scrcpy client does). But I don't know where the "more than one device/emulator" error was thrown.

I have added a copy feature in the packet log page. Can you please:

1. Go to the demo
2. Connect to your device wirelessly
3. Go to "Scrcpy" page and press "Start" (without enabling forward connection)
4. After the error popup shows, go to "Packet Log" page
5. Press "Select All" and then "Copy" button on the toolbar
6. Paste all data here.

**Comment by yume-chan** [comment]
Never mind. I found an old device.

Now the Scrcpy client will automatically use forward tunnel if reverse tunnel can't be created. The option is removed.
