### ISSUE TITLE
Add web manifest and service worker to enable install as PWA

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#482]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Runtime

chromeOS 109

### Device

HP chromebook 14A G5

### Describe the bug

the code ` <link rel="manifest" href="/manifest.webmanifest"/>` in the index.html file for the demo is incorrectly linked. If this could be fixed, then people would be able to install the web app as a PWA.

### Steps to reproduce

N/A

**Comment by yume-chan** [comment]
>  If this could be fixed, then people would be able to install the web app as a PWA.

It used to be correct, but now it also requires a Service Worker. Unreasonable and arbitrary restrictions like this is why I don't bother with this "Install Web App" feature.

**Comment by glitch128** [comment]
I have created a pull request at #507 with changes that would apply to the github pages deployment.

**Comment by yume-chan** [comment]
> hey, is the manifest auto-generated as well, or can it be changed manually?

_Originally posted by @glitch128 in https://github.com/yume-chan/ya-webadb/issues/486#issuecomment-1454175996_

It's not: https://github.com/yume-chan/ya-webadb/blob/main/apps/demo/public/manifest.webmanifest

But it's better to be, using the `BASE_PATH` environment variable.
