### ISSUE TITLE
scrcpy fails "Stack corruption"

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#485]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Runtime

chromeOS 109

### Device

Samsung galaxy A53 5G android 12

### Describe the bug

scrcpy exits with this error
`[server] DEBUG: Using encoder: 'c2.exynos.h264.encoder'
stack corruption detected (-fstack-protector)
Aborted `

### Steps to reproduce

1. connect to device
2. open scrcpy
3. press start

**Comment by yume-chan** [comment]
See https://github.com/Genymobile/scrcpy/issues/2841

It's a bug in Samsung ROM. The extra options for improving quality and latency have been disabled for now.
