### ISSUE TITLE
Open Scrcpy client in a popup window

### ISSUE THREAD

**Issue by yume-chan** [yume-chan/ya-webadb#486]
From https://github.com/yume-chan/ya-webadb/discussions/483#discussioncomment-4865259

Change the Scrcpy flow to:

1. Display the introduction, settings, and start button
2. Press start button, switch to mirroring view
3. Add a "Pop up“ button in toolbar, when pressed, a new popup window opens, continuing mirroring the display
4. The main window goes back to 1
5. The popup window only has the toolbar, the video display, and navigation buttons. The "Pop up" button in toolbar is replaced by a "Restore" button, enabled if the main window is in state 1, when pressed, put the popup window back into main window.

Only one window per device display can exist. The start button can be replaced by "Focus display" or "Switch to" when there is already an instance mirroring the selected display. Multiple windows can be opened to mirroring multiple displays concurrently.

**Comment by glitch128** [comment]
quick question, would this display in a minimal display window, or a Picture-in-Picture (PiP) window?

**Comment by yume-chan** [comment]
A normal window. PIP only supports `<video>` tag so can't use that.

**Comment by yume-chan** [comment]
After popping up one Scrcpy window, the main window switches back to options page, so the user can choose another display and press start again.

**Comment by glitch128** [comment]
Sorry, I should have been more clear. I was trying to ask, how would you bridge the gap between windows without connecting to the device multiple times to allow a popout window in the first place?

**Comment by yume-chan** [comment]
The connection to device is managed by the main window, most of Scrcpy code also runs in main window. The video stream is `postMessage`d to the pop-up window to be played, and input events are `postMessage`d back to main window to be sent to device.

It's also possible to use `BroadcastChannel` to allow multiple windows (without opener relationship) to interact with one device, but without transferable objects the performance will be really bad I guess.

**Comment by glitch128** [comment]
oh ok, I didn't know that was possible

**Comment by glitch128** [comment]
hey, is the manifest auto-generated as well, or can it be changed manually?

**Comment by glitch128** [comment]
if you can add `"display-override":["window-controls-overlay"],` to the manifest, then that could allow you to create a top bar that includes controls without having to return to the main window

**Comment by yume-chan** [comment]
Document Picture-in-Picture API has shipped in Chrome 116, so I added support for it (in the new app).

Compared to popup windows, it doesn't have an address bar so more usable space, plus it's always on top (floating/topmost). The downside is that there can only be one pip window across the whole browser.

I think I don't need to add popup window support, because it's only a little bit better than the expand mode (fills the whole page) it already has.

Note that in the new app, you can access one device in multiple tabs, as long as you don't close the "controller"/main tab (the one having a small USB icon indicating it's accessing USB devices, in Chrome tab strip). That's because I have implemented a sharing mechanism similar to what I described in https://github.com/yume-chan/ya-webadb/issues/486#issuecomment-1453872730.

**Comment by yume-chan** [comment]
> add `"display-override":["window-controls-overlay"]`, to the manifest, then that could allow you to create a top bar that includes controls without having to return to the main window without making the window taller than the canvas

This sounds strange to me. Window Controls Overlay is in my consideration as it looks better in Electron, I may try this idea then.

**Comment by glitch128** [comment]
about the red title bar, what are your window accent colors in windows settings? because on chromeOS, the title bar is rendered as dark grey, so maybe it's your accent colors, because you're using edge.

**Comment by yume-chan** [comment]
My Windows accent color is blue. I have seen Chrome renders a dark title bar in some screenshots from Google.

I used to see the same red color on other Edge UI parts, so I guess it's caused by Edge not syncing color tokens from Chromium source code, and any missing token fallbacks to red.

**Comment by glitch128** [comment]
oh, ok.
