### ISSUE TITLE
gnirehtet support

### ISSUE THREAD

**Issue by QuarTheDev** [yume-chan/ya-webadb#496]
Is there any chance you could implement [`Genymobile/gnirehtet`](https://github.com/Genymobile/gnirehtet) support? It's by the same people who created `scrcpy`.

Gnirehtet is essentially reverse tethering; it allows devices to use the internet connection of the computer they are connected to.

I was provided a Chromebook and my organisation does not allow the use of Linux development tools, so we're pretty locked down. I use your WebADB tool to use things like `scrcpy` to view my phone screen on my desktop and transfer files. I have no way to reach the internet from my phone while away from home, so the addition of `gnirehtet` would be greatly appreciated.

**Comment by yume-chan** [comment]
I know Gnirehtet, but it won't work on web platform.

Gnirehtet captures and redirects network requests (IP Packet, to be precise) on Android device to computer, then it needs the computer to send the request to its destination and get the response.

It's not possible to send arbitrary requests on Web platform, even the Direct Socket API has extra restrictions. There must be a native program running on the computer.

The now deprecated Chrome App might had unrestricted TCP and UDP sockets. I know Chrome App is still supported on ChromeOS, but I can't develop for that.

After all, considering the complexity to implement this pretty rare feature request, I won't going to do it. You might find other methods, for example using your Chromebook as a WiFi hotspot (modern devices with multiple antennas usually support sharing WiFi hotspot from another WiFi network, I know Android and Windows both can do that), or install and use the Android app you need on your Chromebook.
