### ISSUE TITLE
Add --bypass-low-target-sdk-block to install APK

### ISSUE THREAD

**Issue by upintheairsheep** [yume-chan/ya-webadb#500]
**Is your feature request related to a problem? Please describe.**
Android 14 (Upside Down Cake) blocks older APK files from being installed unless you use this flag: --bypass-low-target-sdk-block
**Describe the solution you'd like**
Just add a simple checkbox for it
**Describe alternatives you've considered**

**Additional context**

**Comment by yume-chan** [comment]
Where does the flag go? `adb install` or `pm install`?

**Comment by upintheairsheep** [comment]
> Where does the flag go? `adb install` or `pm install`?

adb install
