### ISSUE TITLE
add more prominent warning to power menu

### ISSUE THREAD

**Issue by glitch128** [yume-chan/ya-webadb#515]
**Is your feature request related to a problem? Please describe.**
I feel that it could be too easy to factory reset or reboot to boot loader by mistake as it is right now.

**Describe the solution you'd like**
A user confirmation utilizing either a checkbox or a modal window requiring the user to confirm that they know and accept the risks and/or consequences of using the dangerous options to be able to access the options.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yume-chan** [comment]
Added in the new app.

See #576
