### ISSUE TITLE
build products on npm has not been updated 

### ISSUE THREAD

**Issue by qz1543706741** [yume-chan/ya-webadb#527]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

0.0.18

### Runtime

Chrome 111.0.5563.146（正式版本）

### Device

macOs  (arm64)

### Describe the bug

```json
  "dependencies": {
    "@yume-chan/adb": "^0.0.18",
    "@yume-chan/adb-backend-webusb": "^0.0.18",
    "@yume-chan/adb-credential-web": "^0.0.18",
    "@yume-chan/stream-extra": "^0.0.18"
  },
```

### Steps to reproduce

1. yarn add @yume-chan/stream-extra
2. import { WrapConsumableStream, WritableStream } from "@yume-chan/stream-extra"
3. In my project, ts tell me there is no 'WritableStreama','WrapConsumableStream' export from "@yume-chan/stream-extra"

**Comment by yume-chan** [comment]
The next version is not ready. I'm not satisfied with the consumable interface.

**Comment by qz1543706741** [comment]
Could U please tell me how many times will it take？
The version 0.0.17 will cause a problem which I could not push some files into mobile, but it's gone in 0.0.18 in your demo.
I don't no if it's one known bug？

**Comment by qz1543706741** [comment]
If easy for u, please make it. Thanks a lot! By the way, Are u Chinese？

**Comment by yume-chan** [comment]
Version 0.0.19 released.

Any detail (repro code/steps) about the file pushing bug?

**Comment by qz1543706741** [comment]
something wrong may happend that cause the wirteable stream promise is still pending, although I have waited for it about 10min.

**Comment by qz1543706741** [comment]
I guess it was the pipeTo method which caused this problem.And I noticed you use pripeThrough method instead of pipeTo.

**Comment by yume-chan** [comment]
`pipeTo(WritableStream)` and `pipeThrough(TransformStream)` are two completely method. Which `pipeTo` do you think caused the bug?

**Comment by qz1543706741** [comment]
I guess `pipeTo(WritableStream)` method may cause the bug. Because after the `upload` method has been overrided in the file `apps/demo/src/pages/file-manager.tsx`, the bug has disappeared.

**Comment by qz1543706741** [comment]
I noticed that u are in China, could you speek Chinese?

**Comment by yume-chan** [comment]
Yes.

**Comment by qz1543706741** [comment]
老哥，稳

**Comment by yume-chan** [comment]
Demo is not released to NPM, but `sync.write`'s signature did change between 0.0.18 and 0.0.19. It's part of a big change (#510) so I still don't know where the problem lies.

If this issue is still persisting in 0.0.19,  please open an new issue with more detailed reproduce code and steps.
