### ISSUE TITLE
Add more ADB Install arguments

### ISSUE THREAD

**Issue by upintheairsheep** [yume-chan/ya-webadb#535]
https://adbshell.com/commands/adb-install
https://developer.android.com/tools/adb

**Comment by yume-chan** [comment]
Tango already supports all options for `pm install`

https://github.com/yume-chan/ya-webadb/blob/c5786fefd98f9d241dde5f52cdbe606734727137/libraries/android-bin/src/pm.ts#L31-L144

**Comment by upintheairsheep** [comment]
> Tango already supports all options for `pm install`
> 
> https://github.com/yume-chan/ya-webadb/blob/c5786fefd98f9d241dde5f52cdbe606734727137/libraries/android-bin/src/pm.ts#L31-L144

In the Web Interface
