### ISSUE TITLE
引入@yume-chan/adb包时，项目运行报错

### ISSUE THREAD

**Issue by liudiming** [yume-chan/ya-webadb#540]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

0.0.19

### Runtime

Chrome 105

### Device

oppo PHQ110 Android 13

### Describe the bug

我项目是vue2项目，想引入@yume-chan/adb这个做一些事情，但是运行项目的时候会报错，以下是报错信息

 error  in ./node_modules/@yume-chan/struct/esm/basic/field-value.js

Module parse failed: Unexpected token (9:14)
You may need an appropriate loader to handle this file type, currently
no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export class StructFieldValue {
|     /** Gets the definition associated with this runtime value */
>     definition;
|     /** Gets the options of the associated `Struct` */
|     options;

 @ ./node_modules/@yume-chan/struct/esm/basic/index.js 2:0-33 2:0-33
 @ ./node_modules/@yume-chan/struct/esm/index.js
 @ ./node_modules/@yume-chan/adb/esm/packet.js
 @ ./node_modules/@yume-chan/adb/esm/index.js
 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib??ref--13-1!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js&
 @ ./src/components/HelloWorld.vue?vue&type=script&lang=js&
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib??ref--13-1!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.114.77.121:9000&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
 
跪求大佬帮忙看看是什么原因

### Steps to reproduce

1.创建一个vue2项目
2.下载@yume-chan/adb这个包
3.在组件中引入这个包，并且使用
4.运行项目，就会看到报错

另外：我也尝试使用tsx项目，也会报同样的错误

**Comment by liudiming** [comment]
你可以自行用vue-cli命令创建一个vue2项目，我现在这个demo就是用的这个创建项目，然后npm i @yume-chan/adb
`<template>
  <div class="hello">
    <button @click="connectFunc">connect</button>
    <h1>{{ msg }}</h1>
    <p>
      For a guide and recipes on how to configure / customize this project,<br>
      check out the
      <a href="https://cli.vuejs.org" target="_blank" rel="noopener">vue-cli documentation</a>.
    </p>
    <h3>Installed CLI Plugins</h3>
    <ul>
      <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-babel" target="_blank" rel="noopener">babel</a></li>
      <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-eslint" target="_blank" rel="noopener">eslint</a></li>
    </ul>
    <h3>Essential Links</h3>
    <ul>
      <li><a href="https://vuejs.org" target="_blank" rel="noopener">Core Docs</a></li>
      <li><a href="https://forum.vuejs.org" target="_blank" rel="noopener">Forum</a></li>
      <li><a href="https://chat.vuejs.org" target="_blank" rel="noopener">Community Chat</a></li>
      <li><a href="https://twitter.com/vuejs" target="_blank" rel="noopener">Twitter</a></li>
      <li><a href="https://news.vuejs.org" target="_blank" rel="noopener">News</a></li>
    </ul>
    <h3>Ecosystem</h3>
    <ul>
      <li><a href="https://router.vuejs.org" target="_blank" rel="noopener">vue-router</a></li>
      <li><a href="https://vuex.vuejs.org" target="_blank" rel="noopener">vuex</a></li>
      <li><a href="https://github.com/vuejs/vue-devtools#vue-devtools" target="_blank" rel="noopener">vue-devtools</a></li>
      <li><a href="https://vue-loader.vuejs.org" target="_blank" rel="noopener">vue-loader</a></li>
      <li><a href="https://github.com/vuejs/awesome-vue" target="_blank" rel="noopener">awesome-vue</a></li>
    </ul>
  </div>
</template>

<script>
import {Adb} from '@yume-chan/adb'
import {
    AdbWebUsbBackendManager,
    // AdbWebUsbBackendWatcher
} from "@yume-chan/adb-backend-webusb";
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  },
  methods: {
    connectFunc() {
      const devices = AdbWebUsbBackendManager?.BROWSER.requestDevice()
      console.log(devices, '获取的设备', Adb)
    }
  }
}
</script>


<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
`  我提供部分的代码，你帮忙查看一下是什么原因导致的，谢谢！

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/233254859-111bc709-c747-4447-b48b-6884a71825c2.png)

I can't reproduce the error.

**Comment by yume-chan** [comment]
Close as stale. Please provide your full project if you still have issues.
