### ISSUE TITLE
Show server output for "Scrcpy server exited prematurely" error

### ISSUE THREAD

**Issue by jiangyitao** [yume-chan/ya-webadb#542]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Runtime

如图

### Device

如图

### Describe the bug

![image](https://user-images.githubusercontent.com/27462472/233788280-6c86dd52-961c-4101-8744-73814569f853.png)

### Steps to reproduce

如图

**Comment by jiangyitao** [comment]
补充console的报错
![image](https://user-images.githubusercontent.com/27462472/233792142-67fdbc70-4604-4be3-967d-a60c9928a42d.png)
手机是魅族android5.1.1，前段时间是可以用的

**Comment by yume-chan** [comment]
https://github.com/Genymobile/scrcpy/issues/3833

Disable audio and wait for next Scrcpy version.

**Comment by yume-chan** [comment]
Leave this open until I add server output into this popup.

**Comment by yume-chan** [comment]
It has been implemented in the new app.

Read https://github.com/yume-chan/ya-webadb/discussions/576 about the new app.
