### ISSUE TITLE
Display Control & Audio Forwarding not working.

### ISSUE THREAD

**Issue by Antwain-Jordan** [yume-chan/ya-webadb#543]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Runtime

Microsoft Windows 11 Pro N | Version 10.0.22624 Build 22624

### Device

Pixel 7 | Android 13 | UpsideDownCake | Latest Android Beta  

### Describe the bug

The ability to turn the screen on and off does not work using USB or WiFi. Also, I cannot route the audio.

### Steps to reproduce

Troubleshoot steps for Screen On/Off Display
1. Connect via WiFi or USB
2. Switch to SCRCPY & Start
3. In the hamburger menu, select either Turn Screen Off or On. The display remains on

Troubleshoot steps for Forward Audio
1. Connect via Wifi or USB
2. Switch to SCRCPY
3. Scroll down to Forward Audio (Requires Android 11) and switch on.
4. Start SCRCPY
5. Start an application that plays audio. Notice it only plays from device
*I've also tried using a combination of all of the Audio Codecs and Audio Encoders before ruling out that Forward Audio doesn't work. 

[Pixel 7-TangoLog-04.23.23.txt](https://github.com/yume-chan/ya-webadb/files/11304381/Pixel.7-TangoLog-04.23.23.txt)

**Comment by yume-chan** [comment]
https://github.com/Genymobile/scrcpy/issues/3784

These are known issues. Audio and clipboard will be fixed in next version, but there is no solution for turning off screen yet.
