### ISSUE TITLE
Do you have any idea to send request permission to multiple Phone in one request?

### ISSUE THREAD

**Issue by tiennguyen12g** [yume-chan/ya-webadb#553]
When we request permission from the phone, a popup will show in the browser . From this popup, we can choose only one device to send the request permission to the android phone. 
But I have 10 - 100 phones, how can I select all phone and send the request permission to all them?
If we have do the request 100 times,  it is not good for experience.
Hope to see your solution, thank Yume.
From your demo, I can connect multiple device.
![image](https://user-images.githubusercontent.com/40747229/236760068-8561a846-c65f-447d-b936-c2c7f31da5b6.png)

**Comment by yume-chan** [comment]
WebUSB doesn't support that. You can leave your request at https://github.com/WICG/webusb/issues/141.

Next time please post your questions in discussions.
