### ISSUE TITLE
Error: Failed to execute 'transferIn' on 'USBDevice': A transfer error has occurred. even when device is still connected

### ISSUE THREAD

**Issue by zany130** [yume-chan/ya-webadb#557]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Runtime

Windows 11 Vivaldi  6.0.2979.18 (Stable channel) (64-bit)

### Device

Galaxy S23

### Describe the bug

Randomly when using the demo it occasionally gives the transfer error and refuses to reconnect 
(gets stuck on Connecting...Please authorize the connection on your device) unless I disconnect and reconnect the cable from either my phone or laptop

### Steps to reproduce

1. connect device to the demo
2. use any function (see it most on scrpy)
3. see error after about 5 minutes of continuous usage

**Comment by glitch128** [comment]
have you tried using a different cable?

**Comment by zany130** [comment]
I don't have another cable right now I will try when I am home, but its strange the laptop is still seeing the device as connected and so does the demo I just cant connect to adb

**Comment by glitch128** [comment]
also, check to see if your device stops charging when adb disconnects

**Comment by zany130** [comment]
> also, check to see if your device stops charging when adb disconnects

no it keeps charging that's why I don't think it's physically disconnecting

so far I havent been able to reproduce on my linux desktop

**Comment by zany130** [comment]
It was the cable haven't had the issue since switching to another one. Guess it wasn't making good contact or something and power was still going through but data wasn't or something
