### ISSUE TITLE
Add name for public key so it will not be displayed as "nouser@nohostname"

### ISSUE THREAD

**Issue by RikkaW** [yume-chan/ya-webadb#570]
The name is displayed in "Developer options" - "Wireless debugging" - "Paired devices".

![image](https://github.com/yume-chan/ya-webadb/assets/12999176/9b2b3602-3585-447c-8edb-68d529210976)

The current implementation does not set the name of the key, so its name is displayed as "nouser@nohostname". If there are more than one, the user cannot distinguish the source of the key.

The method of adding a name is quite simple, just add "` name`" at the end of `publicKeyBuffer` (note the space before name).

https://github.com/yume-chan/ya-webadb/blob/347beb308ed00a3f4b654537d7b36a030a4123ad/libraries/adb/src/daemon/auth.ts#L102-L107

```js
const name = " webadb"; // a space is required
const publicKeyBuffer = new Uint8Array(publicKeyBase64Length + name.length + 1);
// ... 
publicKeyBuffer.set(Uint8Array.from(Array.from(name).map(letter => letter.charCodeAt(0))), publicKeyBase64Length);
```

![image](https://github.com/yume-chan/ya-webadb/assets/12999176/1ec9c0b2-e50c-45fa-ae1e-6138b3fa6665)

Because I don't know how to pass the `name` is better, so I cannot send a pull request x_x

**Comment by yume-chan** [comment]
I changed the return type of `AdbCredentialStore#iterateKeys` to include an optional `name` field. Developers can provide their own `AdbCredentialStore` implementations to specify the name.

The reference implementation `@yume-chan/adb-credential-web` will set name to `Tango@<hostname>` (e.g. `Tango@www.tangoapp.dev`).
