### ISSUE TITLE
dependencies @yume-chan/adb-daemon-direct-sockets is not found

### ISSUE THREAD

**Issue by ncushujian** [yume-chan/ya-webadb#596]
### Issue Checklist

- [X] I'm using the official demo at https://yume-chan.github.io/ya-webadb
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Runtime

yarn 1.22.19

### Device

windows

### Describe the bug

When i use yarn to install dependencies, report @yume-chan/adb-daemon-direct-sockets @yume-chan/adb-daemon-ws @yume-chan/fetch-scrcpy-server and @yume-chan/tabby-launcher is not found. This causes the web service to not run in local.

### Steps to reproduce

1. cd apps/demo
2. yarn install

**Comment by yume-chan** [comment]
Please read https://github.com/yume-chan/ya-webadb/blob/main/CONTRIBUTING.md for how to use this repository.
