### ISSUE TITLE
Chrome Crash while authenticating devices

### ISSUE THREAD

**Issue by kainbryanjones** [yume-chan/ya-webadb#597]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

0.0.17

### Runtime

Chrome, Windows

### Device

Samsung Tablet S6 Lite - Android 13

### Describe the bug

The line that crashes Chrome is line 115 in file 'adb.ts'

```banner = await resolver.promise;```

I'm not entirely sure what this line does, but it's certainly where the debugger finds the program crashes.

### Steps to reproduce

Unfortuantely I'm not 100% sure on what exactly causes the crash, but generally...

1. Attempt to connect to a device, but decline on the device each time...
2. Do this until chrome crashes.
3.

**Comment by kainbryanjones** [comment]
@yume-chan Please let me know what else you may need and I will happily provide.

**Comment by kainbryanjones** [comment]
After checking the master repo this code ```banner = await resolver.promise;``` doesn't seem to be anywhere in the source code now.

**Comment by yume-chan** [comment]
Does the whole browser crash or only the tab? Or some other behaviors?

I don't know how to debug native crashes, I think you need to report it to Chrome developers at https://bugs.chromium.org/p/chromium/issues/list.

I personally haven't seen any crashes when connecting, but the browser, as a sandbox, should make sure no matter what JavaScript code does, the whole browser don't crash.

**Comment by yume-chan** [comment]
I found a potential cause, see https://crbug.com/1314358#c8
