### ISSUE TITLE
paired success,but connect fail! 

### ISSUE THREAD

**Issue by moxiaohe** [yume-chan/ya-webadb#600]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

0.0.21

### Environment

Mac OS chrome

### Device

OPPO reno 5K android 12

### Describe the bug

Error: Failed to execute 'claimInterface' on 'USBDevice': Unable to claim interface.

### Steps to reproduce

1.

**Comment by yume-chan** [comment]
Do you have Google ADB running? https://github.com/yume-chan/ya-webadb?tab=readme-ov-file#direct-connection-mode

**Comment by yume-chan** [comment]
Close as inactive. Read https://tango-adb.github.io/docs/tango/daemon/usb/create-connection for a more detailed explanation.
