### ISSUE TITLE
rush build encounter error

### ISSUE THREAD

**Issue by jackleibest** [yume-chan/ya-webadb#602]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

0.0.20

### Environment

windows 10

### Device

Not yet

### Describe the bug

when i run rush build got an error. I had tried  npx browserslist@latest --update-db, it was not working neither.

### Steps to reproduce

![微信截图_20231009190438](https://github.com/yume-chan/ya-webadb/assets/56916962/7cd62541-41ad-4084-ae24-2ce51187aa11)

**Comment by yume-chan** [comment]
Close as inactive.
