### ISSUE TITLE
[Suggestion] 'https://app.tangoapp.dev' Has the project been open sourced? Can you refer to the implementation logic?

### ISSUE THREAD

**Issue by JerrySir** [yume-chan/ya-webadb#608]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How can Tango be improved?

'https://app.tangoapp.dev' Has the project been open sourced? Can you refer to the implementation logic?

### How should the API change?

'https://app.tangoapp.dev' Has the project been open sourced? Can you refer to the implementation logic?

### (Optional) Other information

'https://app.tangoapp.dev' Has the project been open sourced? Can you refer to the implementation logic?

**Comment by yume-chan** [comment]
Please choose the correct template and fill it correctly.

> Has the project been open sourced?

No.

> Can you refer to the implementation logic?

It works by sending ADB commands according to user inputs to the device and parse the response.
