### ISSUE TITLE
pnpm i @yume-chan/adb-daemon-usb  ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@yume-chan%2Fadb-daemon-usb: Not Found - 404

### ISSUE THREAD

**Issue by JerrySir** [yume-chan/ya-webadb#610]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

latest

### Environment

latest

### Device

latest

### Describe the bug

pnpm i @yume-chan/adb-daemon-usb
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@yume-chan%2Fadb-daemon-usb: Not Found - 404

### Steps to reproduce

pnpm i @yume-chan/adb-daemon-usb
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@yume-chan%2Fadb-daemon-usb: Not Found - 404

**Comment by yume-chan** [comment]
It's [@yume-chan/adb-daemon-webusb](https://www.npmjs.com/package/@yume-chan/adb-daemon-webusb). The doc has been fixed. Thanks for reporting!
