### ISSUE TITLE
[Feature request] `adb shell input text <my text>`

### ISSUE THREAD

**Issue by garywill** [yume-chan/ya-webadb#617]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How can Tango be improved?

We often want to paste some text to the Android device.
I usually use `adb shell input text <my text>` to do that in terminal, when Android device UI focus on a text box.
Hope we can do the text inputting and pasting easily on webui

### How should the API change?

Developer decide. I'm user

**Comment by yume-chan** [comment]
`input text` only supports ASCII characters and doesn't work when non-English IME is active, so I implemented a similar feature that first sets the clipboard, then simulates a Ctrl + V keyboard shortcut: https://help.tangoapp.dev/blog/2024/10/22/quick-actions/#set-device-clipboard
