### ISSUE TITLE
[Feature Request] Call Android browser, or any binded app, to open a URL

### ISSUE THREAD

**Issue by garywill** [yume-chan/ya-webadb#619]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How can Tango be improved?

```bash
am start -a android.intent.action.VIEW -d http://xxxxxxx
```
will make Android open browser to open the url.

Or
```bash
am start -a android.intent.action.VIEW -d  other-scheme://xxxxxxx
```
will make it open the binded app for the scheme.

So please add `adb shell am start -a android.intent.action.VIEW -d <user input url>` as a feature on webui

### How should the API change?

.

**Comment by yume-chan** [comment]
Sorry for the late response, I was in hospital last week.

> So please add `adb shell am start -a android.intent.action.VIEW -d <user input url>` as a feature on webui

Please tell us why you need this feature so we can find a good place for it in the app.

In my understanding, starting a URL is useful for debugging protocol handlers in your apps. It's not related to any existing features in the Web app, so it might be added to the **Advanced** page?

Note: suggestions for the Web app should go to https://github.com/tango-adb/feedback/issues.

**Comment by garywill** [comment]
> Please tell us why you need this feature 

For example, my Android device has an app called "Bilibili" installed. It has registered itself as opener of url `*://www.bilibili.com/*`.

When I see a good video on `https://www.bilibili.com/<videoid>` on PC, I can quickly use that feature to open Bilibili app on Android and tell it to play that video.

Same apply to Youtube and other websites/apps.

Similarily, some apps like Telegram registers `tg://xxxxx` url

---------------

> I was in hospital last week.

Keep healthy. 
You don't have to feel sorry to users.
We technicians are workers who are in the same side

**Comment by yume-chan** [comment]
Sounds like it should be a share target. Except share target API is hard to use.

**Comment by yume-chan** [comment]
It has been added in version 1.7: https://help.tangoapp.dev/blog/2024/10/22/quick-actions/#open-link-in-default-app
