### ISSUE TITLE
[Feature request] Support of [adb root] and [adb kill-server]

### ISSUE THREAD

**Issue by StephenHoo** [yume-chan/ya-webadb#627]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How can Tango be improved?

1. Sometime the connection returns fail and I should run [adb kill-server] in terminal, can this command be suppoted? 
2. Meanwhile, [adb root] is also an important adb command for me and I found there is no implement in webadb, Is there any solution for this command?

### How should the API change?

Just give an API like adb.power.powerOff()

**Comment by glitch128** [comment]
Adb kill-server can't be used without connection to the device, which is blocked

**Comment by yume-chan** [comment]
> Sometime the connection returns fail and I should run [adb kill-server] in terminal, can this command be suppoted?

In ADB client mode it's already supported: https://docs.tangoapp.dev/tango/server/commands/#kill-server

In direct connection mode it's not possible to connect to ADB server and issue `kill-server` command.

> Meanwhile, [adb root] is also an important adb command for me and I found there is no implement in webadb, Is there any solution for this command?

`adb.createSocket("root:")`

**Comment by StephenHoo** [comment]
Thanks for reply, it helps me a lot! I will try server connection instead.
