### ISSUE TITLE
Module parse failed: Unexpected character '#'

### ISSUE THREAD

**Issue by gxpzy** [yume-chan/ya-webadb#635]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

0.0.21

### Environment

windows, chrome

### Device

Android 13

### Describe the bug

vue3-composition-admin中使用ya-webadb时报错，报错信息如下：
[1]  error  in ./node_modules/@yume-chan/adb-daemon-webusb/esm/watcher.js
[1] Module parse failed: Unexpected character '#'

### Steps to reproduce

1. 下载开源项目：https://github.com/RainManGO/vue3-composition-admin
2. 工程目录下执行yarn，vue-class-component选择8.0.0-rc.1 vuex 选择 4.0.0
3. yarn add @yume-chan/adb-daemon-webusb
4. yarn add usb
5. 修改vue.config.js
```
devServer: {
    hot: true,
    port: devPort,
    open: true,
    noInfo: false,
    overlay: {
      warnings: false,
      errors: false,
    },
  },
```
7. 修改src\views\user-manager\login\Index.vue
```
import { useI18n } from 'vue-i18n'
import { AdbDaemonWebUsbDeviceManager } from "@yume-chan/adb-daemon-webusb";
import { WebUSB } from "usb";
handleLogin: () => {
        const WebUsb = new WebUSB({ allowAllDevices: true });
        const Manager = new AdbDaemonWebUsbDeviceManager(WebUsb); // 这行会导致问题
}
```
8. yarn
9. yarn start // 问题复现

**Comment by yume-chan** [comment]
> 2. 工程目录下执行yarn，vue-class-component选择8.0.0-rc.1 vuex 选择 4.0.0

yarn throws an error:

```
# yarn
yarn install v1.22.19
(node:1117) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning Lockfile has incorrect entry for "vue-class-component@8.0.0-0". Ignoring it.
Couldn't find any versions for "vue-class-component" that matches "8.0.0-0"
? Please choose a version of "vue-class-component" from this list: 8.0.0-rc.1
warning Lockfile has incorrect entry for "vuex@4.0.0-0". Ignoring it.
Couldn't find any versions for "vuex" that matches "4.0.0-0"
? Please choose a version of "vuex" from this list: 4.0.0
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.npm.taobao.org/axios-mapper/download/axios-mapper-0.5.4.tgz: certificate has expired".
info If you think this is a bug, please open a bug report with the information provided in "/app/vue3-composition-admin/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

---

> ```
> [1] error in ./node_modules/@yume-chan/adb-daemon-webusb/esm/watcher.js
> [1] Module parse failed: Unexpected character '#'
> ```

Some loader in the template is too old to understand private class fields (it was supported by every modern browser in 2021 https://caniuse.com/mdn-javascript_classes_private_class_fields). I don't know which one, you need to find them yourself.
