### ISSUE TITLE
Console Error: "Decoder not configured"

### ISSUE THREAD

**Issue by wushanchao** [yume-chan/ya-webadb#645]
### Issue Checklist

- [X] I'm using the library programmatically
- [X] For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.

### Library version

0.0.21

### Environment

win10，ios，android，chrome106

### Device

pc, iPhone 17 ,Android 13

### Describe the bug

When I disconnect, that is, when I execute the code 'STATE.stop();', the console occasionally throws an error saying 'Decoder not configured'.

### Steps to reproduce

other tips
1. spawn options max_size=1280 max_fps=120 send_device_meta=false send_dummy_byte=false scid=43cac6b2 video_codec_options=profile=1,level=2048 video_encoder=OMX.google.h264.encoder audio=false audio_codec=aac

**Comment by yume-chan** [comment]
`Error: "Decoder not configured"` means a `data` packet has arrived before `configurations` packet. But I believe in this situation, it's a `data` packet arrived after `dispose` is called.

It's safe to ignore the error, or stop the piping before disposing the decoder:

```ts
const abortController = new AbortController();
const decoder = new TinyH264Decoder();
videoStream
    // .pipeThrough inspect stream to get video size
    .pipeTo(decoder.writable, {
        signal: abortController.signal,
    })
    .catch((e) => {
        if (abortController.signal.aborted) {
            return;
        }
        console.error(e);
    });

// when stopping
abortController.abort();
decoder.dispose();
```

**Comment by wushanchao** [comment]
3ks
