### ISSUE TITLE
[Suggestion] Support forward command

### ISSUE THREAD

**Issue by fanksy** [yume-chan/ya-webadb#649]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How can Tango be improved?

Can you add forward api?

### How should the API change?

adb.forward.addExternal("local address", "device address");

**Comment by yume-chan** [comment]
> adb.forward.addExternal("local address", "device address");

Forward tunnel is implemented in ADB server, not ADB daemon.

See https://github.com/yume-chan/ya-webadb/discussions/641#discussioncomment-9630956, If you are using direct connection mode, you need to listen the local address yourself and forward the connection to daemon using `adb.createSocket`: https://docs.tangoapp.dev/api/socket/#forward-tunnel

If you are using server-client mode, it's not hard to add forward tunnel commands, but this is not a priority and I'm working on other things right now.

**Comment by yume-chan** [comment]
Please clarity what you want to do, otherwise this issue will be closed.
