### ISSUE TITLE
[Suggestion] Read the websocket link from the url and establish a connection

### ISSUE THREAD

**Issue by zwc456baby** [yume-chan/ya-webadb#676]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How can Tango be improved?

I have multiple mobile devices, but it is not convenient to add them one by one and I hope to establish a connection quickly. I hope this function can be supported.

For example, I have the following adb link:

```
wss://xxx.xxx.com/xiaomi
```
When you access the following link, the web page automatically connects and starts scrcpy
```
https://yume-chan.github.io/ya-webadb/scrcpy?adb=wss://xxx.xxx.com/xiaomi&auto=1
```

The web page reads the URL link parameters and parses and connects

### How should the API change?

The web page reads the URL link parameters and parses and connects

When you access the following link, the web page automatically connects and starts scrcpy
```
https://yume-chan.github.io/ya-webadb/scrcpy?adb=wss://xxx.xxx.com/xiaomi&auto=1
```

### (Optional) Other information

none

**Comment by yume-chan** [comment]
The old demo is deprecated, I don't have time to add new features to it. 

If you are willing to contribute, please open a PR to https://github.com/tango-adb/old-demo
