### ISSUE TITLE
[Suggestion] Can an entrance be opened to facilitate the processing of some simple ADB instructions

### ISSUE THREAD

**Issue by hfyhui** [yume-chan/ya-webadb#691]
### Pre-issue checklist

- [X] I've searched the issue list but couldn't find the feature I want

### How can Tango be improved?

Because of different usage scenarios, it may be necessary to execute some simple ADB commands. However, when attempting to modify based on version 0.0.21, it was found that handling these commands was not as convenient as expected.

### How should the API change?

Same as above, I want to use some native ADB instructions

**Comment by yume-chan** [comment]
Can you add an example of what you want to achieve?

**Comment by hfyhui** [comment]
For example, execute [adb shell service clipboard get], [adb shell pm clear package] and other basic abd commands

**Comment by hfyhui** [comment]
Because it is through the embedded iframe page + browser same-origin policy led to not directly use the navigator. The clipboard. ReadText 】, so we want to, through the base of the adb command the adb shell service clipboard get 】 to get clipboard contents.

**Comment by yume-chan** [comment]
> it is not possible to directly use 【 navigator. clipboard. readText 】

But you can connect to the current device's ADB daemon? That sounds strange to me.

> adb shell service clipboard get

Can be done in one line:

```ts
const result = await adb.subprocess.spawnAndWaitLegacy("service clipboard get")
```

**Comment by hfyhui** [comment]
Thank you very much.

**Comment by hfyhui** [comment]
May I also ask if you can provide an adb command to retrieve the content of the clipboard? I found that after pasting is completed, the project can directly retrieve it, but I want to actively trigger the use of adb to retrieve clipboard information

**Comment by yume-chan** [comment]
Not sure if I understand correctly. If you want to monitor clipboard changes, it's not possible with only ADB. You need to do that using Java like [Scrcpy](https://github.com/Genymobile/scrcpy/blob/0e2d084751b0513f5db1b7e7afc5460766f4b5c7/server/src/main/java/com/genymobile/scrcpy/wrappers/ClipboardManager.java#L212)

**Comment by hfyhui** [comment]
Perhaps there is a problem with what I described. Now in ya webadb, when using the copy function, it prompts' Shell pasted from your clipboard ', so I want to have a callback method after pasting, that is, after the prompt' Shell... clipboard ', because I haven't found any adb command that can directly obtain the content of the clipboard yet

**Comment by yume-chan** [comment]
> Now in ya webadb, when using the copy function, it prompts' Shell pasted from your clipboard '

Where is "the copy function"?

> because I haven't found any adb command that can directly obtain the content of the clipboard yet

Then read and write clipboard also need Java code. This is out of the scope for this project.

**Comment by hfyhui** [comment]
> Where is "the copy function"?

After the WS connection is successful, simply use the keyboard [Ctrl+C], and a prompt will pop up saying 'Shell pasted from your clipboard'
